### ISSUE TITLE
Printer Reset (X-Button), raise Z 20mm

### ISSUE THREAD

**Issue by ManuGithubSteam** [prusa3d/Prusa-Firmware#1111]
Hi

Description says it all.

When i print the first layer and its obvious its going to be a bust, i press the Printer Reset X Button.
Now the printer reloads but the nozzle is still on the first layer somewhere and filament is oozing out or not.

This can lead to blockage as the filament does not get out of the nozzle or it backes onto the layer.

Therefore when X is pressed, the printer should raise Z 20mm so we can rest asured that the filemant can flow out and the nozzle does not bake into the 1. layer.

Thanks

**Comment by GurliGebis** [comment]
There is a small problem, since the reset button is a hard reset (the firmware is not involved) - it is, as far as I know, not possible to detect if it has just powered on or if it was reset.
Maybe something along the line of: If hotend temperature is high enough for the fan to turn on, then raise the hotend a bit.

**Comment by maximlevitsky** [comment]
@GurliGebis After a reset printer knows very well that it was reset, so after a reset it can very well raise Z a  bit.

This once happened to me. The pinda got knocked out in previous print (my fault, turns out that I didn't secure it at all afer last service of the  printer that needed pinda recalibration), so when I started a new print the nozzle started to scratch the bed. As soon as I  noticed, I reset the printer, but then I had to raise the nozzle as fast as I can to prevent it from further damage of the sheet.
