### ISSUE TITLE
Unclear README for compiling firmware.

### ISSUE THREAD

**Issue by TheBuzzAldrin** [prusa3d/Prusa-Firmware#1117]
At the bottom of the 'Development environment preparation' section in the README.md, step #3 asks that you do the following:
"modify platform.txt to enable float printf support: "compiler.c.elf.flags=-w -Os -Wl,-u,vfprintf -lprintf_flt -lm -Wl,--gc-sections""

However it is not explained WHERE this file is located. 

I was having issues getting 3.4.0 to compile, and discovered I edited the wrong file.
There are two that I found while trying to follow the instructions.

In the first attempt I tried to edit the 'platform.txt' in the base of the 'hardware' folder inside the arduino installation location by adding the requested line to the bottom. This did not work and the 3.4.0 firmware refused to compile. 
I then went searching and found one inside the 'hardware/arduino/avr' subfolder, which already has a line containing 'compiler.c.elf.flags' which I edited and THAT allowed the firmware to compile successfully. 

I ask that the README.md be updated with a line under instruction #3 inside the 'Development environment preparation' section explaining how to find the proper platform.txt file.

**Comment by geeksville** [comment]
In fact, if you are editing the README, a better instruction would be to have people just create a platform.local.txt file (which is where local settings go that you don't want blown away by arduino updates.  This also makes it easier because the person is just creating a new one line file.

On my linux machine the file would be at:
~/.arduino15/packages/arduino/hardware/avr/1.6.13/platform.local.txt

I can send in a PR that fixes the README if you want it?

**Comment by geeksville** [comment]
@PavelSindler I created a pull request for this change if you want it (also happy to tweak/clarify) https://github.com/prusa3d/Prusa-Firmware/pull/1201
