### ISSUE TITLE
Purge Line  Different Lenghts

### ISSUE THREAD

**Issue by christizzz** [prusa3d/Prusa-Firmware#1164]
Hello,

The Purge line are getting different lenghts randomly... the start code is the default one.. sometime it is the short default purge line.. and some times is 160mm long... it seems that the printer has some issue between relative and absolute for this purge line... Relfashing didnt change anything.. it is not so problematic.. but the issue is therr

**Comment by stahlfabrik** [comment]
Yep it has been like that since I got my MK3 last year. Sometimes it is double length

**Comment by Moorviper** [comment]
do you use different materials then it would make sense

**Comment by christizzz** [comment]
Same Gcode...on the Sd card produced 2 different lenghta... shortt lenght: 100mm which is the normal behavior...as in Move in X to 60 then move to 100... The Long purgelines occurs if i have stoped a print before, using the Stop print in the menu.. and starting a new print will generate this long purge line... it is exactly 160...some how it switches to relative system.. it moves 60 then it moves 100.... which makes 160mm purge line... why does this occur after stoping a pprint ? no idea

**Comment by Panayiotis-git** [comment]
IIRC, I had the same problem sometime ago with the MK2.

You can add the g-code G90 to the start g-code of your printer profile, just after mesh bed leveling.

It will switch the printer to absolute positioning mode.

**Comment by Area5142** [comment]
From time to time, I have seen this randomly longer purge line since I got the MK2.
It is also mentioned in this thread on the forum:
https://shop.prusa3d.com/forum/general-discussion-announcements-and-releases-f61/print-keep-stopping-to-unload-and-load-filament-t23245.html#p99172

**Comment by AbeFM** [comment]
Two nights ago mine went so far that it ran off the end of the bed and triggered a stall-and-rehome

**Comment by GWdd** [comment]
I have the had the issue since new, never been a problem.  But, caught a file that does it repeatedly; every time.  The cause was a typo on my part; but the result exactly mimics the random events I've seen. 

In the repeatable case, I shot myself in the foot and used G92 when I wanted to use G90 as part of an anti-ooze strategy. The fact it mimics the hiccups, it might be useful (.1. file).  It seems the printer - for whatever reason, glitches into relative mode during purge.  

That Slic3r sometimes inserts code between the Custom Printer gcode is a concern, since it adds the chance of other processes corrupting the command. As Slic3r did here (.1. file): I tried removing the extra timer lines to no effect.
```
G1 X60.0 E9.0  F1000.0 ; intro line
M73 Q0 S106
M73 P0 R105
G1 X100.0 E12.5  F1000.0 ; intro line
```

[PurgeFail.zip](https://github.com/prusa3d/Prusa-Firmware/files/2713338/PurgeFail.zip)

**Comment by AbeFM** [comment]
How did it go? I've noticed this as well.

                  Thanks!
                          -Abe.

**Comment by wavexx** [comment]
Also #1494
