### ISSUE TITLE
Just an idea about Prusament and exactly know filament diameter.

### ISSUE THREAD

**Issue by JoschaMiddendorf** [prusa3d/Prusa-Firmware#1222]
I just had an idea witch I would like to share with you guys.
With the use of Prusament and an exactly known filament diameters over the length of it...
Regardless if that's totally overkill at an deviation of under 20µ.
Wouldn't it be interesting to dynamically variate the Extrusion multiplier over the length of the filament extruded?

Points to consider:
- How to log the extruded length?
- How to exactly mark the starting point?
- ...

**Comment by hoppke** [comment]
Huh. Interesting!
- yeah, prusament probably needs it the least :)
- what difference in print quality would it make in real life?
- the controller board might just not have enough power to deal with it (but add a RaspberryPi to the printer and something like Klipper should be able to pull it off easily?)
- I wouldn't trust the starting point very much - each load/unload of filament adds uncertainty, bits get cut off, moisture/temperature may affect it too. I'd prefer markers along the length of the spool, but... optical? mechanical? magnetic? Not ideal, because you'd need to alter the filament.
- If you could reliably measure the diameter yourself without affecting the filament path, then you could do this with any filament
- If, however, you could somehow use Prusa's data, you'd gain one more feature for free -- awareness of how much filament remains on the spool (so the slicer/octoprint could predict if the next print will run out of filament, and maybe even tell you after how many minutes/layers?)

Anyway, I think designing extruder gears(?) that sense the diameter of the filament passing through and adjust the speed/steps automatically is easier to achieve ;)
