### ISSUE TITLE
Octoprint wont connect to mk2.5 FIRMWARE 3.4.1

### ISSUE THREAD

**Issue by BotleHewer** [prusa3d/Prusa-Firmware#1232]
I could not get my octopi to connect with 3.4.1, I just flashed 3.4.0 and it connected right away.

Prusa mk2.5
Octopi on RPi2

**Comment by Tech-outreach** [comment]
had the same issue, Octoprint . Can't find the baudrate with 3.4.1, I reinstalled 3.4.0 and had no issues with Octoprint

**Comment by sky4055** [comment]
same issue here, i downgrade to 3.4.0 and had no issues.

Prusa mk2.5
Octopi on RPi3

**Comment by tibahut** [comment]
Same issue with PC USB connexion. A fallback to 3.4.0 firmware makes it work again.

**Comment by Karkovski** [comment]
same here. downgrade to 3.4.0 fixed it.

**Comment by KarlZeilhofer** [comment]
On the MK3 (with MMU2) it works without issues. Connected to a PC running Debian.

**Comment by Picazsoo** [comment]
Same issue on my mk2.5 - had to downgrade to 3.4.0

**Comment by ram64** [comment]
I am experiencing the same issue with firmware version 3.4.1 on my MK2.5. The printer resets when OctoPrint tries to connect but OctoPrint shows as not connected.

**Comment by asterixorobelix** [comment]
I am experiencing the same problem with Octoprint and firmware 3.4.1
I have even downgraded the firmware all the way to 3.1.1 and the problem still occurs.
See my issue on Octoprint's github: 
https://github.com/foosel/OctoPrint/issues/2843#issuecomment-428698447

**Comment by gertlind** [comment]
Same for me with Prusa 2.5, No octoprint. It says it connected but i cannot do anything with the printer.

**Comment by owey71** [comment]
I set baudrate to AUTO and managed to connect to lower baudrate(57600). Higher than that won't connect.

**Comment by Tchoubaka** [comment]
I just finish my upgrade from MK2S to MK2.5 and install the latest driver. Then I was able to connect via USB and flash the firmware to the latest version 3.4.1-1356. Now I cannot connect to my printer via USB with Slic3r Prusa 1.41.0, always get the error: connection failed. Event if a see some action (character change for square when the connection start) on the display of the printer. I try to change the speed to 57600 but did not work. I will try to downgrade the firmware to 3.4.0.

Update: I just install the firmware 3.4.2-1360 and now the usb connection work fine at 115200.

**Comment by owey71** [comment]
> I just finish my upgrade from MK2S to MK2.5 and install the latest driver. Then I was able to connect via USB and flash the firmware to the latest version 3.4.1-1356. Now I cannot connect to my printer via USB with Slic3r Prusa 1.41.0, always get the error: connection failed. Event if a see some action (character change for square when the connection start) on the display of the printer. I try to change the speed to 57600 but did not work. I will try to downgrade the firmware to 3.4.0.

Try baudrate to **AUTO**. When I tried today I was able to connect to 115200. Something is wrong since last time it was lower. I also managed to move my printer up and down after connecting.
<img width="320" alt="screenshot 2018-10-17 at 1 16 51 pm" src="https://user-images.githubusercontent.com/35494261/47063779-4cd26780-d20f-11e8-9ca7-763efa089cc5.png">



----- terminal log -------
Connected to: Serial<id=0x6d927830, open=True>(port='/dev/ttyACM0', baudrate=115200, bytesize=8, parity='N', stopbits=1, timeout=10.0, xonxoff=False, rtscts=False, dsrdtr=False), starting monitor
Starting baud rate detection...
Changing monitoring state from "Opening serial port" to "Detecting baudrate"
Trying baudrate: 115200
Send: N0 M110 N0*125
Recv: echo: 3.4.1-1356
Recv: echo: Last Updated: Oct  4 2018 17:44:04 | Author: (none, default config)

**Comment by oddworld19** [comment]
I can confirm this issue using Prusa MK2.5 on Firmware 3.4.1 and Octoprint 1.3.10. 

Does anyone know if this is an issue with Prusa firmware or Octoprint?

Octoprint 1.3.10rc1 was just released here https://github.com/foosel/OctoPrint/releases/tag/1.3.10rc1. Has anyone installed it to confirm the issue persists?

**Comment by AMFkuna** [comment]
Strange thing,
I have same issue, but..
I have enabled filament sensor and baudrate set to AUTO, printer connects after some time.
If I disable filament sensor and set baudrate to AUTO, printer not connects and cycling with trying baudrates.
If I set baudrate to 115200 and have disabled filament sensor, printer connects immediately.

**Comment by leptun** [comment]
Had the same problem on my mk2 with custom 3.4.1 firmware. The fix was manually adding “start” to serial at begining of the connection since it was missing.

**Comment by yschroeder** [comment]
From how I understand the problem, it is a race condition between Octoprint and the printer firmware. Octorpint sends an `M110` to say hello to the printer. The printer would normally answer `ok`. However, Octoprint sends this before the printer is even accepting commands via serial (printer sends its normal serial output, you can see it in the terminal tab) so Octoprint gets no `ok` back and thinks the printer is not there.

If you choose auto baudrate, it will send the `M110` multiple times (per baudrate) and the printer is able to answer to one of the retransmissions and the connection is properly established.

There are two ways to fix this:
1. Prusa makes sure, the printer accepts serial commands as fast as possible
2. Octoprint allows some delay before sending an `M110`

I filed an issue for this with Octoprint:
https://github.com/foosel/OctoPrint/issues/2893

**Comment by foosel** [comment]
@yschroeder there's actually a third way: The firmware does what it should do and sends a `start` when it has initialized its serial line. That will make OctoPrint try another `M110`. 

Why does OctoPrint send an `M110` right on connect anyhow? Because there are printer controllers out there that *don't* reboot on serial connect, which also don't send anything on serial connect that would allow communication to get going, so OctoPrint has to do the first step and tries to perform a handshake in case it's connected to such a machine. If it isn't, that machine will (usually...) then send a `start` and all that wall of text on boot up anyhow, and OctoPrint will realize "oh, look at that, it's a printer and it just started, let's try the handshake again". There's even the existing option to have OctoPrint wait until it sees that `start` before it even sends *anything* (because some controllers really don't like it when they get any data before they are fully there yet). 

But without this firmware here sending this `start` message even though it's restarting, it's making things tricky. I honestly don't want to have to add exceptions and special settings for various firmware variants out there all the time to work around their specific quirks, especially if new quirks get added through firmware updates constantly. That simply doesn't scale and becomes a horrible mess to maintain.

**Comment by DRracer** [comment]
Is this issue present in the latest FW 3.9.1? If not, we'd like to close this issue.

**Comment by AMFkuna** [comment]
No this issue NOT present in 3.9.1.

**Comment by rubin110** [comment]
Seeing this issue (or something similar) with 3.11.0. Selecting `AUTO` for the port fixes the issue.
