### ISSUE TITLE
RE: Firmware 3.4.1 on i3 Mk3 nozzle crashing into bed

### ISSUE THREAD

**Issue by jlmyra** [prusa3d/Prusa-Firmware#1248]
I selected a gcode file to print from the sd card. While the bed and nozzle were heating I raised the print nozzle by holding down the selector knob to clean the nozzle. I raised it about ~75mm. When the print began the nozzle moved to x=0, y=0 to begin the calibration the nozzle crashed into the PEI sheet. The z-axis servos continued to force the nozzle into the bed until I shut the printer off. Some how the z-calibration was corrupted when I changed the z-axis position while the bed was heating during a print.

**Comment by titoxd** [comment]
I can confirm, this happened to me as well yesterday. 

I raised the z axis about 120 mm, and the printer did not finish raising the extruder to the desired height before the nozzle reached the desired temperature, which started the print. (It probably got about 75 mm)

The printer tried to lower the extruder as if it were 120 mm above the print bed (instead of the 75 mm where it actually was), crashing the nozzle into the heated bed and gouging the PEI sheet.

**Comment by 3d-gussner** [comment]
@jlmyra Is this still an issue? If it has been fixed in a newer firmware version, please close this issue.
[stale]
