### ISSUE TITLE
No Z High shown on Display just a ?  FW 3.4.1 on mk2.5

### ISSUE THREAD

**Issue by galluslongus** [prusa3d/Prusa-Firmware#1250]
I compiled 3.4.1 on my own cause of PWM_MOTOR_CURRENT Settings. I use different Motors.
After Flashing new FW Z High on the Display is shown just the "?".
I did flashing compiled FW from Prusa´s website and theres all like it should.
I just edited the configuration_prusa.h for PWM_MOTOR_CURRENT settings, nothing else.
Anyone an idea?

Thanks
Michael

**Comment by rpisarew** [comment]
I have the same issue. I cloned the MK3 branch, adjusted the homing currents and stall guard thresholds, because I got 3 of this [steppers](https://www.omc-stepperonline.com/nema-17-bipolar-45ncm-64ozin-2a-42x40mm-4wires-w-1m-cable-and-connector-17hs16-2004s1.html) for x/y/e and they didn't home properly with the default settings.
After a G28 is see only a '?' at the z-positon on the LCD.
When I try to run the first-layer calibration, than I see only a '-' in the z-offset.

**Comment by Barnabasek** [comment]
See #1117 and #1157

**Comment by rpisarew** [comment]
@Barnabasek Thank you very much!, worked well for me.

**Comment by galluslongus** [comment]
I have 7 of the platform.txt in different folders on my system. Its a macbook pro / High Sierra.
I pasted the line in all these files BEFORE i opened this post with no luck.
Is it a hidden file?

**Comment by Panayiotis-git** [comment]
The correct file is the one referenced at the https://github.com/prusa3d/Prusa-Firmware/issues/1117:
hardware/arduino/avr
The file already contains the property and you should change the value.

If the problem still exists after the change, consider reinstalling the arduino IDE (prefer the portable version).

**Comment by rpisarew** [comment]
@galluslongus create a '~/Library/Arduino15/packages/rambo/hardware/avr/1.0.1/platform.local.txt' with this as content

```
compiler.c.elf.flags=-w -Os -Wl,-u,vfprintf -lprintf_flt -lm -Wl,--gc-sections
```

**Comment by galluslongus** [comment]
Awesome, that platform.local.txt did it. Thanks a lot to all Members who helped.
