### ISSUE TITLE
Faster Move Between Autolevel and Print Start

### ISSUE THREAD

**Issue by PotatoFi** [prusa3d/Prusa-Firmware#1286]
The Prusa MK2S with the latest firmware moves slowly between the auto-level sequence and the beginning of the print. There's no bug or anything... the head just moves slowly which gives a bit more time for filament to ooze out of the nozzle.

It would be nice if it was a very fast move from the auto-level sequence, back to near home, so that the print would start faster and there would be a bit less ooze.

**Comment by Panayiotis-git** [comment]
What if the auto-level sequence visited the points in reverse order?

**Comment by JohnOCFII** [comment]
One way to avoid the issue is to do a two-stage heat-up of your hot-end in your startup Gcode.  Warm hot-end to 160C or so; heat the bed to desired temp.  Run the mesh bed level.  Hot-end is warm enough to soften any filament on the nozzle, but not warm enough to drip.  Once the mesh bed leveling is complete, raise the nozzle a bit, and continue to heat the hot-end to the desired print temp.  It's pretty straightforward to do in your startup GCODE.

**Comment by PotatoFi** [comment]
> What if the auto-level sequence visited the points in reverse order?

That would work, but you'd then want to move the hotend quickly to the back of the bed to begin the process. Speeding that move up seems like the easiest way to fix it. The printer does WAY faster moves during normal print operations... we're probably talking about changing one value here to fix it.

> One way to avoid the issue is to do a two-stage heat-up of your hot-end in your startup Gcode.

I suppose that would work... but it comes back to the initial question of, "Why not make this one move be faster". 

Thank you for the recommendations!

**Comment by fiveangle** [comment]
It’s been suggested several times along with optimized probe point order and even dual purge lines (for before and after probes) but interest quickly wanes 🤷‍♂️

**Comment by fiveangle** [comment]
I wish I could solve all my customer complaints by just ignoring them 😝
