### ISSUE TITLE
Z calibration value ignored on MK2.5 with disconnected MMU2.0 ? FW 3.4.2

### ISSUE THREAD

**Issue by Kolous** [prusa3d/Prusa-Firmware#1293]
It seems that the Z calibration value is ignored when printing with disconnected MMU2 unit (MK2.5, firmware 3.4.2).

On left is the piece from the end of 1st layer calibration, It can't be sqeezed any further down. On the right side is whatever other object I try to print. It barely holds to the bed because Z starts to high. It seems that Z is not adjusted bz the value set during the 1st layer calibration (0.850).

![p_20181102_163523](https://user-images.githubusercontent.com/10906901/47926270-7a323d00-dec0-11e8-9415-814e27242cdf.jpg)

**Comment by AbeFM** [comment]
My z-heights vary a ton since I put the MMU on. I thought it was my new R3 parts, but they were there for months before the MMU.

It's very inconsistent lately, but I'm unsure how to test it. I would **REALLY** appreciate some interactivity with the developers so I could provide useful data/insights. I have to change the z-height with each print now, it's like the bad old days of just using a limit switch.

If someone has a suggestion, I'd love to hear it!

**Comment by JohnOCFII** [comment]
> If someone has a suggestion, I'd love to hear it!

GitHub issues are not for general support.  They are best used for focused, clearly defined software issues.  I recommend you connect with Prusa using their Chat service available on the shop page at https://shop.prusa3d.com/   You'll need to be logged in for the Chat tool to appear.  I can also recommend the Prusa forums at: https://shop.prusa3d.com/forum/index.php
