### ISSUE TITLE
Changing plates

### ISSUE THREAD

**Issue by Frigo007** [prusa3d/Prusa-Firmware#1336]
Hi,

When changing a sheet from a smooth to a Textured PEI, the height Z must change as each sheet is otherwise high. To change the height, you need to start printing and then change the height. For me, this is specifically for the smooth sheet -0.286 and for the Textured PEI plate -0.592. Therefore, it would make it easier to work if it was possible to select in the menu or shortcut what kind of plate was used.

Thank you

**Comment by stahlfabrik** [comment]
Well. In the Menu you CAN configure live z even when not printing. That should be what you are looking for?

**Comment by lokiidesigns** [comment]
I don't disagree with the sentiment of using Live Z height adjustment however if I were continuously swapping between smooth & textured plates I would want a stored value against each so that I can select the build plate when I swap them instead...

In the meantime it is a simple as recording the two Z Height values and changing this each time a swap is made but seems like a non-intuitive means to achieve this.

**Comment by mcstoufer** [comment]
This appears to beg the questions of would we then need to track the z height on each side of a given plate independently? Or is the height delta of each side pretty close?

**Comment by Mjankor** [comment]
This would be great. I running printbite on one side of a sheet, and pei in the other. They are quite different in thickness.

**Comment by michalxfanta** [comment]
That's a good idea, thank you. We will consider its implementation in future releases.

**Comment by GreenShadowMaker** [comment]
I look forward to having different saved live z heights for different sheets.

**Comment by michalxfanta** [comment]
In firmware 3.8.0 we implemented Sheet profiles feature.
