### ISSUE TITLE
Firmware 3.5.0 - purge line issues after cancelled print

### ISSUE THREAD

**Issue by insanity67** [prusa3d/Prusa-Firmware#1370]
Hi,
if I pause a print, then cancel it and run the same print again without resetting the printer, it somehow skips the purge line. The printer moves above the spot, but no purge line is extruded. It begins to print the new skirt, and after some time filament is coming out of the nozzle.

I´m on the 3.5.0 from Prusa downloads with stock MK3.

Best regards,
Bastian

**Comment by inquisitiveKangaroo** [comment]
Hi,
did you performed the bowden calibration for each filament? Simillar thing happend to me too. Sometimes a string remains in the bowden and the filament has higher friction then. I set up my bowden cal. slightly under the bontech and since then it has never happened again to me. Sometimes it purge more than neeeded into the wipe tower but prints became much more reliable.

**Comment by insanity67** [comment]
Hi, no I did no calibration, I dont have a MMU(2).

**Comment by mujido** [comment]
I have also seen this with the mk3 and 3.5.0 firmware. Seems like it does an excessive retraction and takes a while to get material back out.
