### ISSUE TITLE
Regular extruder temperature drops with firmwares 3.5.0 and 3.5.1

### ISSUE THREAD

**Issue by Niphargusproject** [prusa3d/Prusa-Firmware#1405]
Maybe related to issues  #1362 and  #1368

With update 3.5.0 on my stock Mk3, I got little temperature drops (~10°C maybe more) on the extruder. I noticed those while looking at the octoprint temperature graph (every 30 min or so). I am generally not next to the printer so I can't tell if the temperature drops trigger "hotend temperature runaway" alarms, but the prints succeded. However this seems due to the 3.5.0 firmware update, as I could not replicate this moving manually the printer head (no bad contact) and these drops disappeared as soon as I reverted back the firmware to 3.3.1!

As I could find other users with the same problem on the forum, I think there is an issue with this firmware, especially as the temperature drop are really close to the delta-T that triggering alarms (15°C if I am not mistaken).

Oh yes : I am printing in **stealth mode**, didn't try in normal mode.

**Comment by tobymurray** [comment]
I see this also on 3.5.0 on my stock MK3 in normal mode. Trying to compensate seems to have put me square in #1362 territory:

![image](https://user-images.githubusercontent.com/3683198/50037477-a8d32580-ffdf-11e8-8302-605f87728f42.png)

You can see the temperature drop when the fan kicks on. I knew it was coming (it just failed last time I tried this print), so I paused the print and turned the fan on full speed to see if it could sort itself out. From there you can see it struggle to maintain temperature. I upped the target temperature to try and compensate and nothing happened, so dropped it back down. That's when I got the PREHEAT ERROR and it aborted the print.

**Comment by bionno** [comment]
So with 3.3.1 you did not notice any temperature drop ?

**Comment by tobymurray** [comment]
I rolled back to 3.4.1 everything appears to work as expected in that version. I did use 3.3.1 when it was the latest and had no issues. I didn't try 3.5.1, anticipating it still being broken as both these issues are still open.

**Comment by tobymurray** [comment]
I rolled back to 3.4.1 everything appears to work as expected in that version. I did use 3.3.1 when it was the latest and had no issues (other than some "time remaining" quirks). I didn't try 3.5.1, anticipating it still being broken as both these issues are still open.

**Comment by cnlson** [comment]
@PavelSindler There is a full thread on prusa forums on this can you please investigate?

https://shop.prusa3d.com/forum/general-discussion-announcements-and-releases-f61/blips-in-temperature-not-seen-before-fireware-3-5--t26121.html

**Comment by Photogad** [comment]
When can this be fixed?

**Comment by crashtest22** [comment]
This is also happening to me on 3.5.1 with new machine and flash/reflash.
I even spent several days on the chat with 2 different people before I started looking elsewhere. 
I have even had one CSR send me another thermistor with no change. 
I am VERY surprised the CSR's don't know of this issue that it seems many have had. I added a post on that thread with my temp dips. 
Can we please get this sorted out so I can print on this amazing machine as it was intended to print with the latest firmware :)

**Comment by lord-carlos** [comment]
Same issue here. Tempature drops, sometimes followed by the printer pausing with HEATING.
Also like some other people say I get temperature runaway error while initial heating at times.

![unknown 1](https://user-images.githubusercontent.com/155855/51661992-bc948300-1fb2-11e9-8a7c-5652469febb9.png)
![unknown](https://user-images.githubusercontent.com/155855/51661993-bd2d1980-1fb2-11e9-95d9-41cc83c9a3d4.png)

**Comment by avirtuos** [comment]
Same here. Brand new prebuilt mk3. My first 3 prints were fine, then the new firmware message popped up. Post upgrade I see 5-10c drops in temp periodically for short periods (usually 10 - 30 seconds)

**Comment by lord-carlos** [comment]
I rolled back to 3.4.1. Everything seems to work.

**Comment by Photogad** [comment]
So can't they just rollback whatever caused it from 3.4.1 -> 3.5.0

**Comment by CNCKitchen** [comment]
Some problem here with my Mk2.5. Just rolled back yesterday to 3.4.1 and everything seems to be fine again (same G-Code):
![dw442wfxcaexwu5](https://user-images.githubusercontent.com/11601966/52175334-73a6b080-27a2-11e9-85e8-1506504ea79b.jpg)
![2019-02-03 10_39_18-octoprint](https://user-images.githubusercontent.com/11601966/52175335-75707400-27a2-11e9-8081-0f820aff907b.jpg)

**Comment by TurboMech** [comment]
I’ve been printing with my Prusa from 210C to 380C extruder (65w heater and PT100 sensor) and have yet to see this on 3.5.1. 

Could this potentially be when your fan kicks up to 100%? This could be an issue with you running in Stealth Mode? Lastly have you completed a PID tune of your extruder?

Edit: I also don’t use the filament sensor. Could you try disabling that for a print to see if anything changes?

**Comment by lord-carlos** [comment]
> Could this potentially be when your fan kicks up to 100%? 

No, I have a sock and it happens even on PLA prints where the fan is 100% active all the time.

>This could be an issue with you running in Stealth Mode?

I don't run in stealth mode so I doubt it.

>Lastly have you completed a PID tune of your extruder?

Yes, I have done the PID tune.

> Edit: I also don’t use the filament sensor. Could you try disabling that for a print to see if anything changes?

Have not tried it, but the printer just stops with the message "heating" would be weird if that was a fillament sensor issue.

I might even revert to 3.3.1 as I  don't have an MMU anyway and there have been plenty of bugs in the last few releases.

**Comment by tobymurray** [comment]
This is nothing to do with anything but the firmware. On my stock MK3, running out of the box PLA profiles not in stealth mode with no filament sensor enabled after thousands of hours of successful prints, 3.5.0 (and 3.5.1) fail obviously. It's not a subtle "maybe it could be..." phenomenon, it's an in-your-face show stopper that's clearly visible on a temperature graph. There's an arbitrary seeming temperature drop, which often leads to clogs. While I've seen many others running into it, I'm surprised _everyone_ isn't blocked by this.

I would imagine a heater that's half again as powerful could hide this. Have you looked at a temperature graph closely to confirm you're not getting irregular temperature dips? I don't mean to be confrontational, but I have a vested interest in this being fixed (I love printing), and I'd hate for a reader to think this issue isn't easily reproducible or well understood.

@TurboMech - completely unrelated, do you have a resource for how to install the PT100 and have everything work out? I'm interested (and the 65w heater too...).

**Comment by CNCKitchen** [comment]
> I’ve been printing with my Prusa from 210C to 380C extruder (65w heater and PT100 sensor) and have yet to see this on 3.5.1.
> 
> Could this potentially be when your fan kicks up to 100%? This could be an issue with you running in Stealth Mode? Lastly have you completed a PID tune of your extruder?
> 
> Edit: I also don’t use the filament sensor. Could you try disabling that for a print to see if anything changes?

Definitely a firmware or defaults settings issue. 3.4.1 works perfectly. Did several PID tunes at different temperatures, positions and fan settings without any change in behavior.
This is a pretty serious issue for me at the moment because I had a couple of high-temp prints with expensive filament fail due to the temperature drops.

**Comment by lord-carlos** [comment]
Mhh, quick question. With 3.5.X I had **two** issues.

* Temp drops that I see in OctoPrint
* Extruder stopping midt print with \*heating\* message on LCD. Continuing after a few seconds leaving zits and drops behind.

Are those the **same** issue? I have not looked at it in detail before I reverted.

**Comment by AnHardt** [comment]
I still miss a temperature plot from RepetierHost with the heater power plot on, or a simple log of the M105 responses. From that one could see if the power is actively dropped by the firmware, or if the temperature drop comes from extern and PID is just reacting to slow.

**Comment by rennne** [comment]
Maybe this issue is related to:
[3.5.2 heat bed temp fluctuations](https://github.com/prusa3d/Prusa-Firmware/issues/1542)

**Comment by darBis** [comment]
Personally i would not completely rule out hw issue. I had experienced similar smyptoms. Somewhat periodic drops in temperature and occasionaly runaway protection triggered.

In my case it was caused by a faulty wire(!) from manufacturing. There was some sort of brekage of wire. When print head got in the right position for just the right amount of time, weird stuff started to happen. There was no visible damage but an "autopsy" after replacing the cable revealed the root cause, beakage at 1/3 of the cable length. After replacing wires from themistor to printer the issue was gone. Just my experience and solution to issue with similar symptoms.

**Comment by avirtuos** [comment]
FYI, I recently updated to the official Prusa firmware (Beta) which has 7x7. I've noticed two issues that went away when i reverted back to the community firmware discussed in this issue. 

1. Layer shifts -I've had one layer shift in the previous 1200 hours of printing. After updating to the official beta w/7x7 certainly models which printed fine previously now have a very similar layer shift 100% of the time. 
2. The bed leveling changed significantly and the first 1cm (exactly) of the left side of my bed was too high no matter what I did with my nylock bed leveling. The only thing that helped was the bed level correction on that side. with the community firmway i didn't need any bed level compensation.

This data is just annecdotal but I'm running more tests to see what gets fixed by reverting, reslicing, etc...

**Comment by holgerurbanek** [comment]
@darBis I'm a bit embarrassed by this comment: Do you really think, all those bug-reporters (here and in the prusa-forum) are having a defective contact, all with the exact same issues? And that this defective contact can be cured just by downgrading the firmware? 

Or, might it be more probable, that there is a race condition somewhere within the firmware, possibly triggered by using octoprint?

**Comment by darBis** [comment]
> @darBis I'm a bit embarrassed by this comment: Do you really think, all those bug-reporters (here and in the prusa-forum) are having a defective contact, all with the exact same issues? And that this defective contact can be cured just by downgrading the firmware?
> 
> Or, might it be more probable, that there is a race condition somewhere within the firmware, possibly triggered by using octoprint?

Since the issue I was having was dependent on current printhead position, previously unnoticed HW issue could manifest like in user reports simply by change of sampling rate or averaging of a measured thermistor value.

I agree, it is quite unlikely for all of those users to have a bad thermistor wiring. I was merely suggesting a thing to check to confirm a firmware issue.

Have this issue been resolved by any of the reporters? I fixed mine by replacing broken wires. :-)
