### ISSUE TITLE
Inserting SD card during auto loading filament cause weird movements 

### ISSUE THREAD

**Issue by rennne** [prusa3d/Prusa-Firmware#1476]
Firmware Version 3.5.0 
Prusa Mk3

1.) Auto Load Filament
2.) Before this is finished insert SD card.

Observerd behaviour:
1.) z-axis menu is displayed.
2.) Display output is similar to a reboot. 
3.) x and y axis start to move fast, and very intense vibrating while doing so.

It seemed like a selfdestruct sequence.
Haven't observed it further because, I pressed "reset" to stop selfdestruct.

**Comment by workinghard** [comment]
I think this issue is in the category "Don't try this at home" :)  
Adding/removing sd card is critical for the controller. You're getting a lot of electrical noise during this process. It might interfere with the time critical communication (like stepper motors). 
This issue might require deep investigation and might also be not reproducible all the time.
