### ISSUE TITLE
[3.7.0-RC1] Extruder crash into X Endstop before Mesh Leveling

### ISSUE THREAD

**Issue by Nippylicious** [prusa3d/Prusa-Firmware#1674]
do you guys have this behaivour?

1. first the Y Axis touches smoothly the Endstop
2. second X Axis (Extruder) toches smoothly the Endstop
3. the extruder moves up a bit and to the right side X Axis
-- so point 1 to 3 are normal --

4. then the Extruder "chrashes" into the X endstop before it start the mesh leveling

I took a video and packed it into a zip
[Extruder_Endstop_Crash.zip](https://github.com/prusa3d/Prusa-Firmware/files/3002219/Extruder_Endstop_Crash.zip)
------
_Originally posted by @Nippylicious in https://github.com/prusa3d/Prusa-Firmware/issues/1651#issuecomment-476100870_

**Comment by mgg4** [comment]
I also had similar issues (https://github.com/prusa3d/Prusa-Firmware/issues/1645), with the crash happening before the first point (front left) is checked.  It proceeded to do all 9 (or 49) points, and then reported the crash.  The mesh bed leveling process repeated, but this time without the crash.

I had occasion to tear down my hot-end to clear a nasty clog.  Upon rebuild, I ran through the full Wizard to test and recalibrate everything.  Since that time I have not had any further issue with this crashing.  From this, I surmise that something about the 3.7.0 firmware is using (or misusing) a calibration value which is interpreted differently than previous versions of the firmware.

In any case, you might try doing a full calibration using the Wizard as a workaround to see if this helps you.

**Comment by Kolous** [comment]
I had this issue when upgraded to 3.7.0RC1. Had to force push the x carrige left and then I glued a 1mm thick stripe on the x carrige to trigger X enddstop.

**Comment by Kolous** [comment]
Also I rearanged the cabeling to be sure (there is not enough space) but this wasn§t the cause of the issue. After 10 attempts I removed the stripe and it works now. This convinced me that it is more firmware than hardware issue.

**Comment by Nippylicious** [comment]
i think this is definitely a firmware issue, because the first time it touches the endstop gently and the second time it ram / crash into.

**Comment by Kolous** [comment]
Mine was crashing even the first time.

**Comment by cyberboom2** [comment]
My mk3 crash same (#1645)

**Comment by PavelSindler** [comment]
What happens if you home axes (calibration->autohome) and then go to "settings -> move X" and go to minimum X coordinate. Does it crash? Is it possible to go to X = 0?

**Comment by Nippylicious** [comment]
When i "home" it, then the extruder touches gently the endstop (as it always was)

The crash is after home before mesh Leveling.

In 3.6.0 there is Not such a behaviour

**Comment by ZachHenkel** [comment]
Also present on MK3

**Comment by Alandovos** [comment]
Also seeing this in MK3

**Comment by PavelSindler** [comment]
I have found MK2.5S printer on which I can see this behaviour finally!

**Comment by PavelSindler** [comment]
Ok, it has been fixed now. Thanks for help.

**Comment by cyberboom2** [comment]
Are ots been fixed on mk3

**Comment by MarcoZ76** [comment]
> 
> 
> Ok, it has been fixed now. Thanks for help.

When will you correct the firmware?

**Comment by dikodahan** [comment]
I have just experienced it as well. Any time frame estimate for the release of an updated firmware for this issue?
MK3S with MMU2S.

**Comment by cyberboom2** [comment]
Its crashing anyway

**Comment by cyberboom2** [comment]
> Ok, it has been fixed now. Thanks for help.

its crashing anyway

**Comment by cyberboom2** [comment]
Its minimum coardinate is +003.2  MK3

**Comment by cyberboom2** [comment]
And its crashing

**Comment by cyberboom2** [comment]
Well done Pavel its not crashing anymore , works fine 7x7
