### ISSUE TITLE
Pausing print then changing filament causes the layers to shift

### ISSUE THREAD

**Issue by mrjohnc** [prusa3d/Prusa-Firmware#170]
Pausing the print and then changing the filament does something where the printhead starts again forward of where it is supposed to start 

Latest firmware, latest Prusa Slic3r

![img_20170812_173940](https://user-images.githubusercontent.com/7293392/29243159-c1d1d9be-7f98-11e7-9a2f-d9656a699861.jpg)

**Comment by 3d-gussner** [comment]
If you want to change the filament during the print and you are not using gcode to do that, then there is a 'Change filament' option under 'Tune' during the print. Maybe that helps. Advantage of this that the nozzle heat stays at set temperature, while pause will set nozzle temp to 0!

You should try PrusaControl, even it is still a beta, but has a nice feature to add filament changes, even if you import gcode.

BTW
I tried to pause, unload filament, tune (nozzle temp to 210 because it was dropping), load filament and resume print and it worked without layer shifting. I use fw 3.0.12-3

**Comment by mrjohnc** [comment]
Thanks, I used the change filament option to do this. I'm not sure why we are getting different results....

**Comment by 3d-gussner** [comment]
That is really a strange! Which fw version do you have? Does it happens all the time or sometimes?
