### ISSUE TITLE
MK2S firmware compiling issue (verification error)

### ISSUE THREAD

**Issue by hackinistrator** [prusa3d/Prusa-Firmware#1706]
i'm having an issue with compiling the latest firmware to my MK2S .
getting ver. error 0x3c000 , which is probably size issue .
i was compiling the same firmware before many times with some tweaks without any issue . 
current size is 251 kbytes (when i compile is says 97% of memory usage) and failes when uploading with this verification error .
when i download pre compiled firmware its smaller , around 235kb 
is something wrong with my arduino or maybe the rambo? tryed to reinstall it and didnt help .
i'm using 1.6.8 and always used it without issues .
any help would be appreciated

**Comment by mkbel** [comment]
We are using Arduino 1.8.5 with some modifications, see https://github.com/prusa3d/Prusa-Firmware/blob/MK3/README.md, or https://github.com/mkbel/PF-build-env/. There is later gcc compiler which uses global optimization and is producing smaller hex. Maximum allowed image size is 248 kB. Memory usage in percents reported by Arduino is wrong, due to error in board definition. see https://github.com/ultimachine/ArduinoAddons/pull/3
