### ISSUE TITLE
3.7.0.Final - Failing Calibration

### ISSUE THREAD

**Issue by sopis** [prusa3d/Prusa-Firmware#1718]
Hello

I just updated my perfectly calibrated Prusa MK2.5S BEAR with 0.04 skew to FW 3.7.0.
1. First of all, the 7x7 mesh bed leveling did not trigger - it was standard 9 points calibration
2. Cannot finish XYZ calibration - after all 4 points are probed, it will state XYZ calibration failed (even though the machine was perfectly calibrated before FW upgrade)

**Comment by michalxfanta** [comment]
Hello, 
1. You have to change 3x3 to 7x7 at _Settings > Mesh bed leveling_

**Comment by sopis** [comment]
Hi Michal

Thanks for the info.
What about the calibration?

**Comment by michalxfanta** [comment]
Could you send to us logs from XYZ calibration? Connect printer with USB cable, run Pronterface, connect printer on baud rate 115200, run XYZ calibration again. Thanks.

**Comment by sopis** [comment]
Hi Michal

Thanks for the tip..once I get home I will run the calibration and log it...

**Comment by sopis** [comment]
Hi Michal

2 logs attached:

1. FW upgrade
2. XYZ calibration

[FW_upgrade_log.txt](https://github.com/prusa3d/Prusa-Firmware/files/3069825/FW_upgrade_log.txt)
[XYZ_calibration_log.txt](https://github.com/prusa3d/Prusa-Firmware/files/3069826/XYZ_calibration_log.txt)

**Comment by sopis** [comment]
To compare, I flashed back to 3.6.0 and did the calibration successfully - log attached.
Results:

Y distance from min:
Left: 8.92mm
Right: 8.63mm

Measured skew: 0.07
Point offset:
X -4.92mm
Y 0.43mm

[XYZ_Calibration.txt](https://github.com/prusa3d/Prusa-Firmware/files/3069871/XYZ_Calibration.txt)

**Comment by cimoalpacino** [comment]
Your calibration points are way off.
it shoud be {x,y}:
{12, 6} ; {220, 6} ; {220, 198} ; {12, 198} mm
snippet from xyzcal.cpp: 
const int16_t xyzcal_point_xcoords[4] PROGMEM = {1200, 22000, 22000, 1200};
const int16_t xyzcal_point_ycoords[4] PROGMEM = {600, 600, 19800, 19800};

Your point are:
{7.29, 4.53} ; {215.14, 4.21} ; {219.39, 203.78} ; {7.50, 196.45} mm

If you want your calibration to pass, you need to edit xyzcal.cpp to your values
const int16_t xyzcal_point_xcoords[4] PROGMEM = {729, 21514, 21939, 750};
const int16_t xyzcal_point_ycoords[4] PROGMEM = {453, 421, 20378, 19645};

Cheers.

**Comment by Ipirk88** [comment]
I have the same problem:
Failing the xyz or z calibration - but only when i set the Steps/mm for the Z axis not to 400.

When i set M92 Z399.48 then it fails,
when i set M92 Z400 then the calibration is  successfuly.

Is the same on MK3S and MK2.5S
FW bug?

**Comment by sopis** [comment]
@cimoalpacino 

Hi - thanks a lot for your research and insight.
Unfortunately, even though I understand your reply, it is rather too advanced for me...
I don't understand why would my calibrations be off - on previous FW (3.6.0) , I had no problem calibrating...

Could you please explain what it means they are off? Could this be because I have a BEAR upgrade?

As for editing the xyzcal file - the printer actually prints quite well...I see some ghosting due to vibrations (also need to figure that out), however it really prints rather fine...so why am I seeing these issues and should I actually really be concerned?

Thanks!!

**Comment by cimoalpacino** [comment]
Hi.
If you assembled everything correctly, you should be fine.
But to me, there are 2 options:
- you maybe assembled something wrong (check all distances as per bear drawings) 
- you flashed the wrong hex or config file. 

Try to reflash the firmware with the modification mentioned above and see if it passes the test. 

Xyz calibration may find all points, but if they are too far from what is set in xyzcal_point_xcoords[4] and const int16_t xyzcal_point_ycoords[4], then the calibration fails.

Otherwise your printer will print just fine and everything will work, the only think that will be disabled is skew correction. 
Skew correction will be enabled once you pass xyz calibration. 
Cheers.

**Comment by gregsaun** [comment]
The Bear frame use the same position as the Original Prusa frame so that should not be a problem.

However, since MK2.5S/MK3S, the original extruder went smaller in height and Prusa updated the calibration to increase Z height. The Bear extruder for MK2.5S/MK3S currently in development is not going to follow that road for two main reasons: print quality and angled fan. Once the release of this extruder is going to be online it will be explain clearly what procedure to apply to get XYZ calibration.

Finally, lots of people with MK2.5 have reported 3rd and 4th point calibration error since firmware 3.1.4 when Prusa introduced a new XYZ calibration algorithm, including on stock frame. Several people have identified were this issue comes from and have reported to Prusa but we still have no fix for that.

**Comment by cimoalpacino** [comment]
Hi,

if Z height is the problem, you just need to edit one piece of code in `ultralcd.cpp`.
Look for the code below and edit the value after Z_MAX_POS.
If Prusa added Z height, then you decrease the number.
Example: if the Z travel distance is 2mm higher, then instead of `Z_MAX_POS+4`, you use `Z_MAX_POS+2`.  

    // Let the machine think the Z axis is a bit higher than it is, so it will not home into the bed
    // during the search for the induction points.
	if ((PRINTER_TYPE == PRINTER_MK25) || (PRINTER_TYPE == PRINTER_MK2) || (PRINTER_TYPE == PRINTER_MK2_SNMM)) {
		current_position[Z_AXIS] = Z_MAX_POS-3.f;
	}
	else {
		current_position[Z_AXIS] = Z_MAX_POS+4.f;
	}
    plan_set_position(current_position[X_AXIS], current_position[Y_AXIS], current_position[Z_AXIS], current_position[E_AXIS]);
`

**Comment by fbujold** [comment]
Can you give the therorical zmax value. I Do mot know if i Shall go plus or minus un the zmax value

**Comment by cimoalpacino** [comment]
When you do xyz calibration and your nozzle is far from bed (you can clearly see it when it's circling above the bed), you need to lower the current_position[Z_AXIS] value. Because you can't change Z_MAX_POS, you just change (lower) the number after the plus sign.

**Comment by brotherdust** [comment]
My printer (MK3S) is now failing as well. I don't really understand why it's doing this now. =/ All I did was move it to another location. I have attached the output of the XYZ calibration routine below. Can someone please have a look and tell me why it's failing?
Thanks!
[XYZ_calibration_log-2019-05-09.txt](https://github.com/prusa3d/Prusa-Firmware/files/3163696/XYZ_calibration_log-2019-05-09.txt)

UPDATE: Loose X-axis pulley. =) Disregard.

**Comment by cwbullet** [comment]
Has Anyone solved this?
