### ISSUE TITLE
3.7.0 - Nozzle temperature drop after first layer

### ISSUE THREAD

**Issue by francisdb** [prusa3d/Prusa-Firmware#1735]
After upgrade MK3 -> MK3s with new firmware
`Slic3r PE 1.41.3+` / `fw 3.7.0`

The temperature drops from 215C to 200C while it's doing the outer perimeter

Movie showing the issue https://youtu.be/_sFY5GL0AWk

**Comment by michalxfanta** [comment]
Hello, could you send us GCODE from video?

**Comment by francisdb** [comment]
[Outer_Ring_v1_0.2mm_PLA_MK3S.gcode.txt](https://github.com/prusa3d/Prusa-Firmware/files/3084805/Outer_Ring_v1_0.2mm_PLA_MK3S.gcode.txt)

**Comment by leptun** [comment]
I am also having this problem. It is on a mk2.5s (r4 extruder). At first I thought it was because of the heater since it was only 35w when measuring resistance.

The actual problem was the print fan. On R4 it blows a lot more on the hotend than on R3. The heater is barely able to keep up when the fan is at full power. 

A silicone sock on the hotend will definately help, but this is a design issue and should not happen at all.

Also it wasn’t pid to blame since it climbed really slowly to the target during calibration with fan on

**Comment by francisdb** [comment]
> A silicone sock on the hotend will definately help, but this is a design issue and should not happen at all.

I added that during the upgrade but my first prints failed so I removed it again, I guess the latest print fan shroud is not really compatible with the sock.
