### ISSUE TITLE
Self Test doesn't notice that IR sensor is missing

### ISSUE THREAD

**Issue by selectnone** [prusa3d/Prusa-Firmware#1745]
(**prusa3d_fw_3_7_0_MK25S**)

I have found that the Self Test did not report any problems when my IR sensor wasn't plugged into the Rambo board.

Because of this, I spent far too much time trying to get the filament sensor to respond!

If this sensor's presence can't be detected automatically, the user should be asked to perform a filament-insertion test instead, to make sure it's working as expected.

**Comment by leptun** [comment]
It can’t really notice if the IR sensor is present since it has no conplex logic. Also prompting the user for a filament test is not possible as the hotend test only heats up to 100*C and there might be filament loaded, so unload is impossible.

A walkaround would be to ask if filament is present and tell the user to unload before selftest and tell the user to insert filament when checking for it. 

Will try to do it myself and post it here if it’s succesful. I’ll also make a pull request
