### ISSUE TITLE
TMC2130 Stallguard TH HOMING XY not taken from config

### ISSUE THREAD

**Issue by NielschB** [prusa3d/Prusa-Firmware#1753]
in FW 3.7.0 on MK3, the homing stallguard thresholds for XY in file tmc2130.cpp are hardcoded instead of taken from configuration_prusa.h. See file tmc2130.cpp line 41, harcoded value 3. configuration_prusa.h has the homing threshold defined around line ~250.  (Would be nice to split the X,Y,Z homing SG thresholds in the config)

**Comment by jenda122** [comment]
I think this should be made configurable not even at compile time, but in the menu/eeprom.

Additionally, I'd really appreciate some better diagnostics of the stallGuard than displaying the average value during selfcheck. The average may not tell you everything if there are sudden glitches (the minimum value would be more interesting), and it is also cumbersome to run the selfcheck just because of this. For example I would appreciate to get this diagnostics on every homing.
