### ISSUE TITLE
add quick access menu

### ISSUE THREAD

**Issue by TonyLHansen** [prusa3d/Prusa-Firmware#185]
I've often thought that there needs to be a "quick access" top-level menu that offers a few simple commonly-used items that are otherwise buried rather deep. For example, "move Z up 5cm". (Yes I know that there is no buried menu item that says "move Z up 5cm", but that is something I find myself wanting to do quite often.) The items that are available on this "quick access" menu should be individually choosable.

**Comment by 3d-gussner** [comment]
I guess coding this personalized menu would take a lot of effort and still not everybody would be able to get what they want.
You have to remember that this controller uses a atmega 2560 8-bit chip with LIMITED CPU power and ressources and its primary function is translating gcode to as far as possible accurate physical movements and print results.
If lot of people could agree to ONE version of quick access, that could be done.

**Comment by ceryen** [comment]
This isn't exactly what you asked for, but here's a useful tip: if you long-press the button, it'll jump into the Z-axis position screen, which will allow you to quickly move the Z-axis

**Comment by tkircher** [comment]
It would be easy to set up a Raspberry Pi with a touchscreen that interfaces over USB, if you want more sophisticated control right at the printer.

**Comment by clearbucketLabs** [comment]
The menu could just be based on SD Card gcode in some folder.  like "quickaccess" and the name of the menu item is the name of the gcode minus extension.  it would be similar to just going to print from SD card but i guess filtered for just those operations so you don't have to scroll through your print files.  only disadvantage would be it's on the SD card, if you have more than one then it would have to be cloned to others.

i think physical quick access buttons are better though since they're truly quick access.  like load filament/unload filament/preheat/move Z up.     Normally i would attach to some IO pins and execute gcode for that...  RPI works too but that's overkill for just buttons.

**Comment by inquisitiveKangaroo** [comment]
Move Z-axis shortcut has been implemented.
