### ISSUE TITLE
electric noise hot bed 3.7.2 rc1

### ISSUE THREAD

**Issue by austaquio32** [prusa3d/Prusa-Firmware#1925]
good morning, after updating to 3.7.2 rc1he noticed a substantial noise in the print base after warming up to maintain the temperature, I saw that the bed pwm was implemented, with the two printing bases makes me noise and not It is very nice, does this have a solution?

**Comment by rlightner** [comment]
Noticing this as well.

**Comment by DRracer** [comment]
If you mean the audible sizzle coming from the bed, it is not an electrical noise ;) . The bed behaves like a loudspeaker and the 30Hz PWM responsible for switching heating on and off makes this sizzle. Right now we are working on a silent solution to this problem, we hope to have this fixed in FW 3.8.0.

**Comment by ochm** [comment]
Duplicate with #1862
