### ISSUE TITLE
Feature Request: LCD knob acceleration

### ISSUE THREAD

**Issue by haarp** [prusa3d/Prusa-Firmware#1961]
Turning the knob to scroll through large ranges, e.g. from 0°C to 250°C, takes a lot of time and effort. Each click of the knob corresponds to one unit of change.

I think acceleration would be a nice addition to the knob. Turning it slowly should continue to step through 1 unit at a time, but turning it at higher speeds should progressively step up the unit-per-click ratio.

Example:
Turning the knob 40 clicks (2 revolutions) in 5 seconds or slower -> 40 units are changed
Turning the knob 40 clicks in 2 seconds -> 80 units are changed
Turning the knob 40 clicks in 1 second -> 160 units are changed

These obviously need fine-tuning. A similar concept has been successfully used for a long time for computer mice.
Cheers!

**Comment by ManuGithubSteam** [comment]
Very good idea. I second this.

**Comment by maximlevitsky** [comment]
I too would like that implemented.

**Comment by GWdd** [comment]
Since most acceleration schemes fail for the stupidest reasons, and the response time of the EINSY selector wheel is already problematic, why not make the increment of large scale items like temperature steps of 5 or 10 degrees.   In 99% of cases, you don't need single digit precision.  

Or, do a Press and Hold to increment digit selection. Default to 10 degrees per step, press and hold to rotate through the digits, cursor shows which digit is being modified.

**Comment by romeoalfa1975** [comment]
Ich fände es schon hervorragend, wenn das Menü bei jedem Klick des Drehknopfes überhaupt reagieren würde. Manchmal reagiert es gar nicht, gelegentlich springt es sogar in die verkehrte Richtung...

**Comment by 3d-gussner** [comment]
> Ich fände es schon hervorragend, wenn das Menü bei jedem Klick des Drehknopfes überhaupt reagieren würde. Manchmal reagiert es gar nicht, gelegentlich springt es sogar in die verkehrte Richtung...

Please write in English as not everyone understands German.

**Comment by romeoalfa1975** [comment]
I would like the menu to react at all with every click of the knob. Sometimes it doesn't react at all, sometimes it even jumps in the wrong direction...
