### ISSUE TITLE
proposal: position of the sheet selection menu

### ISSUE THREAD

**Issue by DesC21** [prusa3d/Prusa-Firmware#2093]
I think it would be nice if you could see which sheet is selected from the main menu before starting a print. When I start a print from the sd card, I have to scroll down to check if the correct sheet is selected. If the menu entry for the sheet selection was higher to the top, for example directly before or after "PRINT FROM SD" (I'd prefer after), the user could immediately see if the print can be started.

**Comment by vintagepc** [comment]
I would advocate for something more visible too; I also nearly did a number on my smooth sheet when I'd accidentally had the printer set to the PC profile. A prompt prior to starting the print could be problematic in the octoprint/remote workflow but perhaps finding a way to display the selected sheet on screen during warmup and pre-heating with the X/Y/Z (X0/Y210/Z50?) in such a position that it's easy to quickly change sheets would be viable. Maybe replace "Bed heating... " with "[Sheet name] heating..."?

**Comment by jbinfl** [comment]
Ohh, I like this suggestion and vintage PCs idea.  that would be very helpful if possible to implement!

**Comment by TehH4rRy** [comment]
This has my vote! I've been lucky to only scuff my PEI by not checking which sheet I have on

**Comment by vintagepc** [comment]
I would be willing to contribute some time to get this implemented and filing a PR; are there any existing leanings from the "official" dev team as to what/how?

Right now I'm contemplating doing something like replacing the %done with the sheet name until the print is underway (since it's obviously going to be 0 until we get up to temp and actually melting plastic), but if there are existing plans for shuffling display elements to accommodate it I would be happy to work within those plans.

**Comment by vintagepc** [comment]
I decided to implement it on the info screen by replacing the percent done when either the printer is heating or there is no percentage (idle). Both regions consume exactly 7 characters, so it works very nicely. PR is filed.

**Comment by DesC21** [comment]
perfect, thanks Prusa Team :-)!
