### ISSUE TITLE
Request: re-home MMU2 on every filament change

### ISSUE THREAD

**Issue by aarchiba** [prusa3d/Prusa-Firmware#2106]
From time to time, depending on how well the MMU2 is working, I find that the idler or selector are not where the MMU2 think they are. Of course this causes failures. Sometimes hitting reset on the MMU2 is a sufficient fix but re-homing the MMU2 doesn't take long, and doing it on every filament change, and before every re-try, would eliminate many of these failures in the first place. 

Of course the selector can't be moved if the FINDA detects filament, but the the idler can.

**Comment by Prusa-Support** [comment]
I'm sorry that the issue has been overlooked
Apparently, so far, the request for homing the Multi Material module between filament changes is not so popular in the community.

The fact that the selector and idler-barrel are often out of sync is an anomaly to be solved through troubleshooting.
Homing the Multi-Material module each time could be a backup solution, but it would enormously extend the already long print times.
Probably solving the anomaly has priority over finding back-up methods. A sporadical anomaly like that may not be so concerning, but if it keeps on occurring it shouldn't be considered acceptable.

Either the idler barrel or the selector skipped steps or encountered resistance.
Please make sure both are correctly assembled and move freely.
https://help.prusa3d.com/en/article/mmu2s-idler-unable-to-move-freely_1996
https://help.prusa3d.com/en/article/mmu2s-selector-not-moving_1997

For more troubleshooting, please consider reaching the Customer Support.
https://help.prusa3d.com/article/customer-support_2287

This issue will be closed because stale.

Michele Moramarco
Prusa Research
