### ISSUE TITLE
[3.8.0-RC1 MK3S] - automatic temp cal. goes on forever

### ISSUE THREAD

**Issue by OskarLeirvaag** [prusa3d/Prusa-Firmware#2121]
### Issue
After updating printer, before anything else, a temperature calibration was started. Knowing it would take a while I left the printer and heard the beep. When returning the printer was still doing step 6/6 and went on for about 30 min before i shut it down.

### HW
MK3S MMU2S

**Comment by leptun** [comment]
Please try again and post a photo with the temperatures menu in the support menu after it gets stuck.

If the noctua fan starts spinning because of extruder temperature over 50c it might cool the pinda enough to not reach the target temperature.

It might also be that it doesn’t reach the temperature because of other factors such as a defective probe. That menu should tell us enough for now.

**Comment by OskarLeirvaag** [comment]
I did not get a picture, and I'm printing right now. Although, I do remember the readings as I was watching them.

Extruder 50c/0c (Noctua on)
Heatbed 109c/110c (Ranging from 109-110).
Room temp 23c

Will post pic if it happens again

**Comment by OskarLeirvaag** [comment]
Oh and "F?" if that is relevant

**Comment by leptun** [comment]
Ummm... I don’t know what “F?” is. Can you explain it further.

**Comment by OskarLeirvaag** [comment]
F? means that the MMU does not know its position as it has not yet been used

**Comment by leptun** [comment]
Oh, ok then. It is not relevant. :)

**Comment by boraca** [comment]
0 degrees means your hotend thermistor is disconnected or damaged.

**Comment by leptun** [comment]
@boraca Ummm, no. The 0 deg is his hotend target, which is as it should.
I asked for the temperatures in order to see the pinda temp and the extruder temp. The thing is that when the extruder fan turns on at 50 deg, it actually also blows some cool air on the pinda preventing it from reaching the expected temperature.

This issue has been reported before, but I can’t find the other posts right now.

**Comment by Sembazuru** [comment]
I've had similar issues with using M860 to wait for 35°C on cold days (bed is only 60°C) as part of my start gcode before mesh bed leveling. Tenting over the PINDA with a bit of paper towel helps insulate it from the room (and trap heat from the bed) to allow the PINDA to finish warming up. Maybe you are seeing something similar with your temperature calibration?
