### ISSUE TITLE
LCD screen not work afterfirmware update

### ISSUE THREAD

**Issue by MikeErmagerd** [prusa3d/Prusa-Firmware#213]
Hi all,

I have been having a heap of trouble with firmware I compiled, after flashing my MK2s the LCD screen becomes garbled looking like

fffffffffffffgggggggggggggggggggvvvvvvvvvvvvvvvvvbbbbbbbbbbbbbbfffffffffffsssssssssssssffffffffffffffgggggggggggggggggfffffffffffffffffgggggggggggggggggggvvvvvvvvvvvvvvvvvbbbbbbbbbbbbbbfffffffffffsssssssssssssffffffffffffffgggggggggggggggggfffffffffffffffffvvvvvvvvvvvvvvvvbbbbbbbbbbbbbbfffffffffffsssssssssssssffffffffffffffgggggggggggggggggfffffffffffffffffgggggggggggggggggggvvvvvvvvvvvvvvvvvbbbbbbbbbbbbbbfffffffffffsssssssssssssffffffffffffffgggggggggggggggggfffffffffffffffff etc

- After resetting the printer the screen becomes alternating rows of white squares and blank rows

- This is my first time so I got a programmer to help me out and we are both getting the same result following the instructions https://github.com/prusa3d/Prusa-Firmware (which are terrible btw)

- There are no compile errors, though two hex files are created...I tested both

Is anyone able to confirm the most recent arduino and prusa driver pack are working on a MK2s?

Any help at all would be appreciated.

Cheers and thanks...Mike

**Comment by 3d-gussner** [comment]
@MikeErmagerd  Sounds bad.

Did you tried to use the Prusa Firmware Uploader which is installed with the drivers http://www.prusa3d.com/drivers/ and re-flashed it back to fw3.0.12 http://prusa3d.com/downloads/firmware/prusa3d_fw_3_0_12.zip? 

Which Arduino IDE version do you use?
I use the newest version 1.8.4 with the Additional Board URL 'https://raw.githubusercontent.com/ultimachine/ArduinoAddons/master/package_ultimachine_index.json' and searching in the Boards Manger for 'RAMBO'. Used in the past the Arduino IDE 1.6.8 with all the changes but don't need it anymore.

When you compile the code and then export the compiled binary make sure that you use the 'Firmware.ino**.with_bootloader**.rambo.hex' file to upload via the Prusa firmware uploader.

**# !!! DON'T USE/UPLOAD THE HEX FILE WIHOUT BOOTLOADER !!!**

Can you still connect via Pronterface (also installed with the Prusa drivers) to the printer via COMx?
If so, try 1st to upload the official firmware 3.0.12.
Otherwise you gonna need to FixMyRambo from Ultimachine. Someone i tried to help also managed to get the miniRambo non responsive and he contacted 1st Prusa and later Ultimachine support.

Hope that helps

**Comment by stephenwhittle** [comment]
@3d-gussner Could the compilation/update instructions be updated to reflect this please? I've encountered the same issue after updating to the version without the bootloader. I assumed that the bootloader would be protected, given that we're uploading via FirmwareUpdater which (I presume) is using said bootloader to perform the upgrade...
Following your instructions here, ie using Boards Manager rather than manually copying files over, I was able to reflash without issues, and I have access to the hardware to reprogram the bootloader if need be, but I expect it would be quite scary for people without access to such.

**Comment by GurliGebis** [comment]
I don't think it is likely that the documentation will be updated. Based on how long the pull request with the updates has been ignored.
Might be to discourage people from messing with the firmware to begin with (fewer support calls from people breaking stuff)

**Comment by leptun** [comment]
@michalxfanta This is very old and doesn't apply anymore. I suppose it could be closed

**Comment by 3d-gussner** [comment]
@MikeErmagerd  Long time no update here. Can you please close this issue?

**Comment by MikeErmagerd** [comment]
Thread closed

**Comment by easonjim** [comment]
#3484
