### ISSUE TITLE
Strange Layer Shift on 3.8.0 RC1

### ISSUE THREAD

**Issue by crashtest22** [prusa3d/Prusa-Firmware#2158]
I had 1 print do a strange layer shift and then corrected about a 20 layers later. was on the x axis. I found no issues with other prints. 
I have now flashed to RC2 and will report any issues.
Printing over octoprint sliced with simplify3d
Mk3 upgraded to Mk3S

**Comment by leptun** [comment]
Things to check:
Check the hardware for loose pulley. It could shift back to the initial position if the screw is slightly loose.

Check if crash detection was turned on.

Check if the model is too big and the X axis might have collided with the axis end. Happened to me before.

Do a selftest as to calibrate the auto-home for X and Y. If you don’t do so, if a crash occurs and is detected it might actually home inconsistently and actually cause the layer shift.

**Comment by crashtest22** [comment]
I did check all pulley's and belts.
All tight and the spec on belt status was in range

Crash detection was on but print was middle of bed and not large
very far from edges. 
I had done self test after print to get belt status and have not had it happen again.
currently printing attached gcode. 
Will report here if it shifts 
[dx9BattCover_1800mahb.zip](https://github.com/prusa3d/Prusa-Firmware/files/3562697/dx9BattCover_1800mahb.zip)

**Comment by crashtest22** [comment]
Here is a few pics and Gcode of the print that shifted
![2019-08-31 11 09 15](https://user-images.githubusercontent.com/46016626/64067595-01833680-cbe0-11e9-9907-706839468c3a.jpg)
![2019-08-31 11 09 01](https://user-images.githubusercontent.com/46016626/64067596-01833680-cbe0-11e9-8f24-b7e4d656944e.jpg)
[Groot_v1_1M_Merged.zip](https://github.com/prusa3d/Prusa-Firmware/files/3562705/Groot_v1_1M_Merged.zip)

**Comment by william14235** [comment]
Mine shifted once too but it only happened once. However it was a small print so I don't think the size has to do with it

**Comment by Prusa-Support** [comment]
This issue was not proved to be concerning the firmware.

Apparently, this issue was not reproducible so it was likely a sporadic sequence of crashes or layer-shifts.
The printer may have detected some crashes along the axis and may have home incorrectly for some reason (similarly to issue #1096). It may have crashed again later and homed correctly.
We cannot even exclude that two layer-shifts occurred one after another in opposite directions, where "almost coincidentally" the second one corrected the print position, as mentioned above in the thread.

This issue will be closed because stale and not reproducible.

Michele Moramarco
Prusa Research
