### ISSUE TITLE
Mintemp error while waiting for MMU user fix, kills the print

### ISSUE THREAD

**Issue by bretcobrageek** [prusa3d/Prusa-Firmware#2299]
I have a MK3S (3.8 firmware) and MMU2S (1.0.6) and print from octoprint. It has started to get cold at nights, but still like to open a small window to have good ventilation in the printer room. But I have discovered that if the MMU has an issue that needs the user to fix something it will park the extruder and turn off the heater which makes sense.

Unfortunately, this means the hot end will reach room temperature which, with the window opened and being below freezing outside, can be under the 15C mintemp limit. Once the mintemp error occurs, the printer must be reset, effectively killing a very long print that could've easily been finished with a simple MMU fix and restart.

Is it possible to disable the mintemp error check when the hotend heater is off like this MMU pause case?  This is a great safety feature, but mintemp check shouldn't matter when the heater is off.  15C is really not that cold for a room temperature and it would be a shame if I couldn't use the MMU during the cold months due to these crashes during MMU pauses.

**Comment by tobymurray** [comment]
Same concern as #1775

**Comment by clintonefisher** [comment]
Ugh.  I run a cold shop and the MINTEMP behavior has been unnecessarily infuriating for me since DAY ONE of owning my two Prusas.   There was a brief shining moment with 3.7.0, that the behavior didn't cause me to have to get the damned blowdryer out, but in 3.9.0-RC1 it's back.
I saw one collaborator in another issue thread blow this problem off by saying that the operating range of the Prusa is 18C-38C.   Seriously?  That's the excuse?  A minuscule 20C operating temperature range?    I can't imagine losing long, many-hour prints due to such a poor design decision.  
Safety and "not ruining the user-experience" can co-exist.
