### ISSUE TITLE
No option to change filament type when loading new filament after unloading filament. (MK3 FW V3.8.1)

### ISSUE THREAD

**Issue by madnats** [prusa3d/Prusa-Firmware#2319]
Have to reset printer to select new filament preset.

**Comment by william14235** [comment]
I think that if the temperature is high enough, to load it can load every filament. However, if the temperature is room temperature, it will give you the option because it needs to heat up anyway. Have you noticed that for loading pla you can load at 208, and for pet you can load at 220? it is the same logic I think.
