### ISSUE TITLE
[BUG][3.9.x] Significant E-axis behaviour difference (breaks prints) from 3.8.1

### ISSUE THREAD

**Issue by vintagepc** [prusa3d/Prusa-Firmware#2514]
**Printer type** - MK3S
**Printer firmware version**-  3.9.0 RC / 3.8.1

**MMU Upgrade** - MMU2S
**MMU upgrade firmware version** - 1.0.6

**Describe the bug**
There appear to be print-breaking E-axis differences with certain gcode combinations that were not present in 3.8.1.
I kept having issues with the attached g-code while running 3.9.0-RC (+ my various PRs merged in). 
Figuring it was something I did, I flashed back to stock RC. No dice.

I went even further back to 3.8.1, at which point the attached g-code prints fine.

In 3.9.0, The perimeter prints fine, but any retraction over-retracts and the rest of the print continues without extruding until the over-retraction gets to the point it trips the filament sensor.

There's something about the way this gcode does retractions that highlights the issue - regular sliced code from prusaslicer prints fine.

( for reference, the attached g-code is a first-layer speed and height calibration generated from 3dOptimizer.com  - it appears to be functional for many people on many makes of printers.)
  
**To Reproduce**
Print the attached g-code on 3.9.0-RC
  
**Expected behavior**
Gcode should print as expected, e.g. as it does in 3.8.1
  
**G-code**
[First_layer.gcode.zip](https://github.com/prusa3d/Prusa-Firmware/files/4269742/First_layer.gcode.zip)

**Video**
~Happy to capture one if necessary; I just don't have the time at the moment to set up a camera/flash versions/etc.~

update: plans changed, captured video. Pay attention to the orange rotating gear during retractions. Exact same g-code, both printers:
3.8.1 behaviour: https://vimeo.com/394576663
3.9.0-RC behaviour: (will upload tomorrow, I hit my weekly vimeo upload limit)

**Comment by leptun** [comment]
Things changed a bit with https://github.com/prusa3d/Prusa-Firmware/pull/2381
Before the change the following combination would result in wrong behavior:
```
G91 ; set ALL axis as relative
M83 ; set Extruder ONLY as absolute
G1 E1 ; should be an absolute move, but still relative
```
With that change the extruder can be absolute even if all the others are relative.
I've noticed some time ago when I tried to use absolute extrusion in PrusaSlicer that it simply did not work. It did something similar to what I experienced with your gcode.
Your problem is that your gcode is relying on `G90` and `G91` to not affect the Extruder relative-ness. That was true in previous firmware, but it was accidental and only worked in edge cases. The marlin documentation states clearly that `G90`/`G91` should also set the extruder and that `M82`/`M83` are simply overrides.
As a potential solutions you can do the following in the unretract snippet:
```
G90
G1 Z0.150000 ; notice the lack of "E0.000000"
G91
```
Or you can add `M83` after every `G90` in your file.

https://marlinfw.org/docs/gcode/G090.html
https://reprap.org/wiki/G-code#G91:_Set_to_Relative_Positioning

**Comment by leptun** [comment]
@vintagepc Do you have any way of testing the same gcode in marlin 2.0?
I'd like to see if it does the same issue also there. It should.

**Comment by vintagepc** [comment]
No, sorry. This is my only printer. I did look at that combo of commands when it initially didn't work, and it left me scratching my head how it was supposed to work, since it does indeed appear to move the E axis to (abs) 0.000 - so it's working "as directed" and "as I read it" in 3.9. Ordoinarily I'd have been fine with that, it just got really confusing when hearing various success reports from others that were able to get it to print, prompting me to go back to 3.8.1 to test. 

There's other weirdness in the generated files from that site; TBH it looks like they were made by someone that doesn't quite get g-code (like the G28 at the *end* of the print, for example) so I don't think I'll lose any sleep over this now no longer working.
