### ISSUE TITLE
[BUG]Possible overflow in Timer class expired() method

### ISSUE THREAD

**Issue by micromouseonline** [prusa3d/Prusa-Firmware#2517]
The Timer class is used in several places to either provide software delays or timeouts for events. 

The expired() method may not produce correct results when the  time register wraps around for the underlying unsigned type.

This is the current code:

https://github.com/prusa3d/Prusa-Firmware/blob/c07814bcad3570c5f2b89cabb0e07fe0ab4cea19/Firmware/Timer.cpp#L43-L65

The problem lies in how the compiler promotes the expression 

     m_started + msPeriod

for the comparison. Depending on the compiler and the target architecture, the expression may be promoted to int and will wrap incorrectly.

The simplest fix is to cast these expressions to the timer register type:

    T(m_started + msPeriod)

A better solution that is smaller, faster and correct would be to replace the expired method with this alternative:

    template <class T>
    bool Timer<T>::expired(T msPeriod) {
      if (!m_isRunning) return false;
      T elapsed = _millis() - m_started;
      bool expired = elapsed >= msPeriod;
      if (expired) m_isRunning = false;
      return expired;
    }

**Comment by mkbel** [comment]
You are right, that there might be problem. But the problem might happen only if we make smaller timer<T>, than is size of type compiler promotes to. At this moment the bug can't manifest, as we explicitly instantiated Timer only for unsigned short and unsigned long. On our platform int is 16 bit, short is 16 bit, unsigned int is 16 bit, unsigned short is 16 bit. So unsigned short gets promoted to unsigned int, and as both types are the same nothing happens. No promotion takes place in case of unsigned long, as unsigned long is bigger than int and unsigned int.

The problem might kick in, if we instantiate Timer<unsigned char>.

"simplest fix" is for sure right, and I don't see any risk.

"better solution" is probably right, it would need more thinking if it is for sure right.

If there would be originally or after fix some catastrophic bug, it would be hopefully detected by unit test, which checks, if Timer handles wraparound well.

It would be good idea to update unit test so it is capable of detect bug caused by integer promotion (instantiate smaller Timer) than is platform int size. (unsigned char should do the trick). Make the test failing and then apply fix.
