### ISSUE TITLE
  [ENHANCEMENT] Skip preheat for MMU eject when filament not loaded

### ISSUE THREAD

**Issue by NielschB** [prusa3d/Prusa-Firmware#2552]
Enter what type of printer or upgrade the enhancement applies to.
MK3S + MMUxS

**Is your enhancement related to a problem? Please describe.**
When selecting eject filament from the menu, the firmware forces the nozzle to be heated end executes the ramming sequence. This is not required when there is no filament loaded in the extruder which saves significant amount of time.
  
**Describe the solution you'd like**
Check for filament load status, if not loaded, skip the preheating and ramming part.

**Comment by Prusa-Support** [comment]
Thank you for reaching us.

[edit] Sorry for the confusion. Yes, basically this feature can also be used mid-print, after pausing, so that an unloading sequence is included.
Not sure if the feature will deserve a re-work for the specific scenario where there is no filament in the nozzle, because the space on the board's memory needs to be optimized to allow the implpementation of new and possibly amazing features, but the developers may look into this.
Thank you for your suggestion.

Michele Moramarco
Prusa Research

**Comment by gudnimg** [comment]
This will be fixed once 3.13.0 is released.

**Comment by gudnimg** [comment]
Closing as this is now resolved with FW 3.13.0 and MMU FW 3.0.0 :)
