### ISSUE TITLE
3.9.0 and Pi Zero W has Err: Part Fan err issue and hang.

### ISSUE THREAD

**Issue by greggree** [prusa3d/Prusa-Firmware#2668]
3 MK3s
3.9.0

While printing through Octoprint on the Pi W on the Einsy, prints randomly stop with Err: Print Fan err and I can't resume. After flashing back to 3.8.1 I disconnected my x axis motor, set the fan to 255 (Really should be going from 0 to 100% in the 21st century). I moved the extruder back and forth the full motion and monitored the Support/Extruder/Fan RPM. It didn't jump around. I did 3 more prints through Octoprint and didn't see an issue. Its not my fan cabling. I can print fine with 3.8.1. Interrupts for the RPM pulses are getting blocked, or bugged, causing a false positive.
 
To repo install a Pi Zero W to the Einsy and print multiple things through the web ui. Random Err: Print Fan err and hangs without resume.

**Comment by jltx1** [comment]
I am having the exact same problem with direct from SD card prints, no Pi Zero.  The interrupt routine seems flaky.  I watch the RPM and it looks fine.  Later I get a random print fail for either fan, print or nozzle.  I look at RPM in support menu and it is way off of normal.  Print fan hovers in low 100-400 RPM even though it is spinning fine.  Suddenly it will drop to zero for a while which, of course, throws an error.  I turn of fan check and can print 8 hour prints no problem.  The tach sense is broken somehow.  I double checked wiring.  Everything is good.  I just looked at the RPM with a cold printer, turned on fan and nozzle to 60C.  RPM for both is around 4000, but they jump around quite a bit, the print fan more so, from 2800 to 5200, but mostly around 4000 by a couple hundred.

And, yeah, fix the fan selection 0 to 100%!  That should be so simple.

**Comment by jltx1** [comment]
further info.  I just did a quick print and watched the support menu, the fans actually got more stable under print load.  The bouncing around seen when cold reduced substantially.  

The failure I observe is intermittent and seems modal.  It's like it gets stuck in this bad place and cannot recover.  When I had the print fail, I left the support menu on so I could watch the RPM while I checked all the wiring and wiggled the connectors at the Einsy.  It never recovered.  I was unable to restart the print because it kept failing out with the same error.  Only succeeded when I turned off fan check, but even then the support menu still showed nozzle fan at >8000 RPM and print fan at 0-180 RPM for the rest of the print.   Other prints, like the one I just did above, are fine the whole time.

**Comment by jltx1** [comment]
I flashed back to 3.8.0 (I still had laying around) and the fan speeds are correctly reported again.  Appears to be 3.9.0 bug.

**Comment by pomidoorq** [comment]
![20200817_203304](https://user-images.githubusercontent.com/61778767/90431172-ec413980-e0c8-11ea-9966-18dca5c3c583.jpg)
Same problem here with 3.9.0. After some time into any print (after random time) there is Err: Print fan error and can't resume. When enabling print fan manually the rpm values are all over the place (check attached photo). The only way to resume printing is to disable "fan check" from menu. Im not using PI, printing from SD. Issue happens only on this FW, 3.8.1 is fine. Einsy Rambo board.

**Comment by DRracer** [comment]
Is this issue present in the latest FW 3.9.1? We did some improvements to ISR handling which may have helped.

**Comment by JohnnyDeer** [comment]
Closing for no response as stale.
