### ISSUE TITLE
[QUESTION] Electromagnetic field on the Heatbed?

### ISSUE THREAD

**Issue by alomex21** [prusa3d/Prusa-Firmware#2697]
Does this affect the MK42 Heatbeds? Some people keep telling me that there are no magnets, which I doubt they read the changelog correctly. My primary question is how did you discover this issue and what result gave so far before this method of turning off the heated?

Cheers.

**Comment by floridaservices** [comment]
Part of the reason that Prusa developed their own board definition for Arduino is because they created their own timer for the heat bed.  I don't remember all the details of it(was a tech blog posting so it was lengthy!) but apparently the old way of doing things made the heatbed "noisy" , like audibly apparently.  I also run a MK42 heatbed, and suffer no ill effects from running 3.9.0 other than having to adjust some mesh_bed_calibration.cpp parameters.

**Comment by alomex21** [comment]
@floridaservices Now I have two questions: How did you get the 3.9.0 with the MK42(or MK2s) and is there any link to that tech blog?

**Comment by leptun** [comment]
For getting a MK2S build with FW 3.9.0, you must compile the firmware on your own.
Link to the blog post he is talking about: https://blog.prusaprinters.org/dev-diary-2-how-we-made-the-heatbed-silent_30946/

**Comment by alomex21** [comment]
Thanks for the link @leptun! I've read the blog(quite cool) but I did not found anything related to the electromagnetic field which my question is still on point.

**Comment by leptun** [comment]
The PINDA v2 had issues during Mesh Bed leveling where if the bed heating PWM was active while probing, then the measurements could be off and the procedure would fail. I'm not sure if magnets have any play in this, but rather the fact that high current is flowing through the bed traces.

**Comment by mullcom** [comment]
I think this soved my issue.. before on 3.8 it sometimes needed to calculate same spot twice. 

Now on 3.9 it do all spots fine as it should be. I also get the value more perfect. But that can be Frome I move the printer to other places.

**Comment by leptun** [comment]
@mullcom It's not just the bed PWM that is affecting the MBL repeatability. During testing me and @3d-gussner discovered that having a spool mounted on top of the frame greatly reduced the wobble in the frame, hence why it failed less often. Unfortunately, my printer runs exclusively on 2.2Kg spools, so I can't mount them on the frame for dampening.

**Comment by mullcom** [comment]
hmm. i still have some trubbel that calibration for mech is stooping mitt in the calibration. and it doing calibration of Z axel. I going to try to get it on camera

**Comment by mullcom** [comment]
Here is a video of the loops it doing after failing the mech bed calibration.

https://photos.app.goo.gl/mHYwsTuggaU3vnFeA


For info 
I use octo print "prusa mech bed calibration" plugin to calibrate the value.  I have the plate on when I do this otherwise it takes on the second last point and sometimes there. Before I start to get trubble I get 3 times in row working calibrations


Did test mesh bed calibration in mk3 settings.
See how it behaves.
https://photos.app.goo.gl/eDwK9rPF2Ay2bVRB8

Wondering if there something else going on here because of the weard sound coming when I reach the top.

**Comment by mullcom** [comment]
I was need to reset printer from beginning and do Wizard calibration. now i can do mech bed calibration
