### ISSUE TITLE
  [ENHANCEMENT] First layer calibration - start in front and work to back

### ISSUE THREAD

**Issue by speed-3d** [prusa3d/Prusa-Firmware#2793]
Enter what type of printer or upgrade the enhancement applies to.
**Printer type** - MK3S

**Is your enhancement related to a problem? Please describe.**
When setting up first layer height, the patter starts in the back of the plate and works its way forward.  This leaves the completed track behind the print head and X-axis structure.  Reversing this pattern (i.e. starting on the front edge of the plate and working backwards) would leave the completed track in front of the x-axis and print head structure.  This would allow for easier (and safer) "thumbnail" testing, assessing the quality of the deposited plastic without dodging the moving print head.
  
**Describe the solution you'd like**
Reverse the first layer calibration pattern to start toward the front edge of the build plate and draw the test traces towards the back of the plate (it does the opposite currently.)

**Comment by wavexx** [comment]
When doing the first layer calibration I look at the printer with an eye at the build-plate height and look at the distance between nozzle/plate. I usually can get perfect results already at the first 3-5cm this way (you can get crazy-good going it by eye). I only look at the corners and extrusion size otherwise when the plate is done.

If the direction would be flipped, the filament would obstruct the visibility.
