### ISSUE TITLE
  [ENHANCEMENT] Reduce MMU2(S) Init/Calibration count

### ISSUE THREAD

**Issue by ggrote** [prusa3d/Prusa-Firmware#2817]
When powering the i3 MK3s printer and MMU2 the MMU2 gets initialized (The selector is calibrating loudly) many times.
It seems like it is calibrating at:

- Power on
- Prusa i3 detects MMU2
- Octoprint connects to printer
- Start print

It should be enough to calibrate the selector wheel just before the print starts. 
Otherwise it is very annoying and loud (especially if no filament is loaded).

**Comment by chriswal** [comment]
This is already implemented (in 1.0.6). when no filament was loaded before a new start the idler and the selector will not home. the filament loaded will be stored in the eeprom. but when unloaded they do nothing (bug). so the idler homes to the last loaded filament position. 
i made a workaround on my firmware to set the filament to 5 on unload (because they started at 0).
for a fix 0 should be unloaded, and 1 to n on load...
perhaps they didnt do it because the write to the eeprom doubles? ....
