### ISSUE TITLE
[FEATURE REQUEST] Sort SD by time needed to build part.

### ISSUE THREAD

**Issue by txstick** [prusa3d/Prusa-Firmware#2818]
MK3S

I do not leave my printer running when I am not home or I am sleeping.

I have to scroll thru the list to search for one that will fit in the time I want the printer to run.
It would be very helpful if a SD sort could be added to allow sorting G-code files by build time.
I would like to be able to change between alphabetic name sort and build time in the LCD options.

**Comment by DRracer** [comment]
You can achieve the same effect by naming your files this way:
`01d03h45m_some_name.gcode` and sorting them alphabetically

Otherwise I see no other stable solution to your request - scanning the filename for potential print time and/or searching comments/M73 inside the G-code files itself would be horribly inefficient on the 8bit board (moreover - also unstable, not every G-code contains these informations)
