### ISSUE TITLE
[BUG]<ORIGINAL PRUSA MINI - Blue screen - TASK: webServerTask>

### ISSUE THREAD

**Issue by Psychorages** [prusa3d/Prusa-Firmware#2821]
Please, before you create a new bug report, please make sure you searched in open and closed issues and couldn't find anything that matches.

**Printer type** - ORIGINAL PRUSA MINI
**Printer firmware version**-  4.2.0-final+2067

**MMU Upgrade** - [e.g. MMU2S, MMU2, MMU1]
**MMU upgrade firmware version [e.g. 1.0.6, 1.0.6-RC2, ...]

**SD card or USB/Octoprint**
  Please let us know if you print via SD card or USB/Octoprint

**Describe the bug**
  Blue screen @ 74% print job :
![20200902_145953~2](https://user-images.githubusercontent.com/52109462/91994292-be016200-ed36-11ea-8678-b63e05084002.jpg)

  
**To Reproduce**
  print with lan on
  
[Base_0.2mm_ABS_MINI_6h46m.gcode.zip](https://github.com/prusa3d/Prusa-Firmware/files/5163075/Base_0.2mm_ABS_MINI_6h46m.gcode.zip)

**Expected behavior**
 no blue screen :')
  
**G-code**
  Please attach a G-code. This will make it easier for us to replicate the error.

![20200902_145953~2](https://user-images.githubusercontent.com/52109462/91994574-0882de80-ed37-11ea-9ed3-06a16395463f.jpg)

**Comment by leptun** [comment]
Hello there
This repository is meant only for the 8 bit Prusa Firmware, so MK3S and earlier. For the Mini Firmware, please post issue reports here: https://github.com/prusa3d/Prusa-Firmware-Buddy/issues

In any case, I think your exact issue was solved in the latest release of the Mini firmware. Try using 4.2.1 and see if your issue is still there: https://github.com/prusa3d/Prusa-Firmware-Buddy/releases/tag/v4.2.1
