### ISSUE TITLE
[QUESTION] Why does the heating bed need to heat when I want to load filament?

### ISSUE THREAD

**Issue by ing-kuczmik** [prusa3d/Prusa-Firmware#2869]
When the printer is cold and I want to load or unload filament. Why does the heating bed need to heat when I want to load filament?
Best regards
Adam

**Comment by neophyl** [comment]
Because you are loading filament the printer makes the assumption that you want to start printing after loading filament.  As it takes longer to heat the bed up this assumption is good for the majority of cases and decreases wait time for that majority of users.
It was probably done that way due to user requests.
If all you want is to do is load filament then you could always navigate to the settings screen and set the extruder temperature to a suitable value, wait till it heats up and then load filament.

**Comment by thehumanfallacy** [comment]
This makes sense as I also usually want to print after loading.  But maybe it could also prompt and ask you if you want to heat the bed?  That should be a quick user interaction if the default value of _Yes_ is highlighted.  Just a thought.

**Comment by Panayiotis-git** [comment]
You can find an ongoing discussion about this subject [here](https://github.com/prusa3d/Prusa-Firmware/pull/2335)

**Comment by Prusa-Support** [comment]
merge with #422
