### ISSUE TITLE
[QUESTION] Nozzle and bed keep heating after Eject fillament procedure

### ISSUE THREAD

**Issue by NightSkySK** [prusa3d/Prusa-Firmware#2877]
Please, before you create a new question, please make sure you searched in open and closed issues and couldn't find anything that matches.

**What is your question?**
Is it expected behavior that nozzle and bed is keep in heating stage after Eject Filament procedure is completed?

Fist of all not in all cases nozzle and bed should be heated as described in [issue#2552](https://github.com/prusa3d/Prusa-Firmware/issues/2552), but even after Eject filament is completed (confirmed knob to hide fillament back to mmu) the nozzle and bed is kept in heating condition. There is high risk that user will keep the printer in this condition if it is not noticed by user.

**Comment by wavexx** [comment]
Yes, it's expected IMHO. The usual scenario is that you're going to load another filament soon. It's rare to just eject the filament.

There's already a discussion going on whether the bed should also be heated when ejecting. See PR #2335. I personally like the behavior of the PR, since I frequently unload a material, then preheat for another which requires different temperatures, so heating the bed is often pointless.

There's a built-in safety timer which kills the heater if the printer is left idle for a while.
