### ISSUE TITLE
[QUESTION]Potential Bugs?

### ISSUE THREAD

**Issue by copalfreak** [prusa3d/Prusa-Firmware#2900]
firmware 3.9.1-3518 on i3 mk3s mmu2s (firmware:1.0.6-372)
(screen says MMU2.. not MMU2s.. normal?)

Trying to load filament into MMU2s (menu->print from SD card->pla->filament 5),
the filament was stuck or something, so I manually cut and pulled it out and re-loaded and told it to resume by pressing the knob on the control board.
It went into an endless loop of ejecting filament out of the front end, about 1/3 meter at a time.

I shut it power cycled it, and when I turned it back on, it did the same.
I powered off and back on again, and depressed the reset button on the board.
Eventually, I was able to start printing a test.. but the filament got stuck again.
I could not pause or abort the print, so I powered it off.
When I power it back on, it said resuming and starting heating up again.
Apparently, there is no menu item to stop the print after a resume from detected power failure.
I disconnected the MMU2 unit and power cycled and that seemed to do something, because it did not try to resume again when I power cycled.

During a re-run of calibration wizard from menu->settings->calibration->wizard,
it failed to recognize there was a mmu2s attached, so when it asked for filament to do the first-layer calibration, it had to be loaded manually. When I say it failed to recognize, I mean it seems like it did not check.. if there had been a way to check in the middle of the procedure, I am sure it would have actually detected it.. It acts like the software routine for this part of first layer calibration may not be setup to look for and work with an attached mmu2s or something.

Can anybody else confirm these types of behaviors?

**Comment by Prusa-Support** [comment]
Hello! I am sorry to intervene on this issue so late. Apart from the 1/3 filament loading, the rest appears to be normal - the fail on loading from MMU2S is likely hardware-related (extra drag or not enough "pulling force" from the MMU2S components, such as tension bolts on the top and also bolts holding the rear PTFE tubes). 

If the issues are still there, can you please let me know via email? info@prusa3d.com mentioning me. I'll look into it and we'll solve it. Closing the issue here as it seems to be hardware-assembly related. 

Alessandro Pantaleo
Prusa Research
