### ISSUE TITLE
[FEATURE REQUEST] Allow tuning of Extruder stepper current while printing

### ISSUE THREAD

**Issue by plampix** [prusa3d/Prusa-Firmware#2912]
I've recently had some problems with some white PLA from a reputable brand. The problems were that on very small layers (small printing time), the extruder started to skip. I realised the stepper driver current was lowered by the start-gcode of the printer profile to 430mA because I used a 'Detail' setting. Increasing the current just for this filament solved my issue. I just added 50mA, and continued printing.

It would be nice if there was a possibility to tune, or even calibrate the extruder stepper current on the printer itself.

**Comment by Prusa-Support** [comment]
Thank you for sharing your ideas.

As you already know, minor current adjustments are possible via M907 code on the Prusa Slicer side (start g-code).
From the official Support point of view, I don't encourage you to alter the default values because excessive values may lead to damages or undesired results, but I believe that a range of 400-600 mA would be safe.

Yet another reason not to alter this value, is that these parameters have been fine-tuned with the slicer configuration update _v. 1.1.8 from 31 July 2020_ - a few months before the issue was posted.
https://files.prusa3d.com/?latest=slicer-profiles&per_page=all
Maybe said configuration update would remove the need for turning the extruder stepper motor current, and there is a chance that the configuration in your Prusa Slicer was not yet up-to-date. In order to avoid missing configuration updates, please make sure that "update built-it presets automatically" is ticked out in Prusa Slicer preferences (top bar | _configuration -> preferences_).

Also, as mentioned in issues #765 and #1757, there may some specific factors for the extruder stepper motor to skip steps. Please check the conclusion of these issues and rule out other possible factors for the motor to skip before tweaking the extruder current.

Also, consider reaching out the Technical Support. https://help.prusa3d.com/article/customer-support_2287

This thread has been silent for more than one year, for this reason, the issue could be closed as stale, but such a feature request sounds legit to me : )
Again, changing the extruder motor current could be hazardous so I'm not sure if live-tuning the extruder stepper current during the print will ever be allowed but, for now, I'd keep it open, and leave the conclusion up to you and the developers.

Michele Moramarco
Prusa Research
