### ISSUE TITLE
MMU2 Loading issues

### ISSUE THREAD

**Issue by MakerJE** [prusa3d/Prusa-Firmware#3002]
Have seen a lot of questions about this from 2018 but nothing to date... maybe there's a fix?? The Prusa MMU2 seems to be a bit tricky.

When printing the bed and hot end heat to temperature. When loading, the selector bearings align with the wrong filament and tries to unload instead of load. Pressing reset button sometimes fixes this and instead progresses to the filament feeding from the wrong selector and the head to receive the filament stays still and begins to feed filament out of the front of the machine.

Anyone else had this issue recently?

Seems the MMU2 unit is miscommunicating, have tried basic troubleshooting and no luck as yet.

**Comment by Prusa-Support** [comment]
Hello! I apologize for the very late response to this issue. Was this resolved in the meantime? 

The main suspected cause for this issue is hardware-related, with the idler not able to move correctly. The very likely causes of this bad movement are related with the flat part of the idler motor shaft not aligned with the flat part of its housing: https://cdn.help.prusa3d.com/wp-content/uploads/prusuki/prusuki-images/xr-2-u-ihuoal-2-cvkv-5.jpg, and/or these two bolts being possibly too tight: https://cdn.help.prusa3d.com/wp-content/uploads/prusuki/prusuki-images/ui-kwj-5-ws-lga-zs-grb.jpg

Let me know, in case of need we can go into more detail to fully solve it! 

Alessandro Pantaleo
Prusa Research

**Comment by gudnimg** [comment]
@Prusa-Support I think we should close this issue once FW 3.13 is released

**Comment by Prusa-Support** [comment]
The MMU firmware was completely rewritten and made more robust too.
https://github.com/prusa3d/Prusa-Firmware/releases/tag/v3.13.0

The new firmware version 3.13.x for Einsy and 3.0.0 for MMU greatly improve the troubleshooting experience and general user interaction. Please give it a try.

The very recent firmware overhaul renders this issue obsolete and therefore the issue will be closed now.

Michele Moramarco
Prusa Research
