### ISSUE TITLE
[BUG] MMU always in Normal mode after reset

### ISSUE THREAD

**Issue by Thf772** [prusa3d/Prusa-Firmware#3068]
**Printer type** - MK3S
**Printer firmware version**- 3.9.3-3556

**MMU Upgrade** - MMU2
**MMU upgrade firmware version** - 1.0.6-372

**SD card or USB/Octoprint** - Not applicable

**Describe the bug**
When resetting the MMU while the printer is powered, the MMU will always be in Normal mode, even if it was configured to be in Stealth mode.
  
**To Reproduce**
1. Power printer
2. Set MMU to Stealth mode
3. Reset MMU (with reset button)

**Actual behavior**
MMU is in Normal mode

**Expected behavior**
MMU is in Stealth mode

Probably related to all other MMU reset bugs.

**Comment by gudnimg** [comment]
I believe this is a bug in the MMU firmware. The problem is the MMU firmware does not store the `Silent Mode` setting in EEPROM memory.

It makes sense to me that the MMU loses its `Stealth Mode` status if there's a reset event. The MMU will enter `Normal Mode` if the Prusa Firmware doesn't activate `Stealth Mode`. The Prusa Firmware -- from what I can tell -- will always activate the MMU `Stealth Mode` unless disabled through the LCD display.

Now say the `Stealth Mode `is active... you reset only the MMU. The MMU will initialise to `Normal Mode` but the Prusa Firmware still thinks the MMU is in `Stealth Mode`. The MMU firmware does not communicate its current Mode to the Prusa Firmware so it has no way to tell that the Mode has changed on the MMU side.

Note: I don't have an MMU to test on, but this is my understanding from looking at the code. 🖨️ 😄
