### ISSUE TITLE
[FEATURE REQUEST] Cancel heating during preheating

### ISSUE THREAD

**Issue by jasonbcox** [prusa3d/Prusa-Firmware#3176]
**Printer type** - MK3S, likely applies to others as well

**Is your feature request related to a problem? Please describe.**
Cancelling a print during preheating results in a long pause until preheating has completed before the cancellation takes effect. If preheating from room temperature, waiting for the bed to reach ASA temps (for example) can take some time, resulting in frustration and wasted time for the operator.

This behavior appears to many users as a bug in different circumstances. See some related issues:
https://github.com/prusa3d/Prusa-Firmware/issues/2862
https://github.com/prusa3d/Prusa-Firmware/issues/3019

Personally, I have encountered this while attempting to cancel a print from OctoPrint. During preheating, the cancel print operation hangs until both nozzle and bed heating have completed.
  
**Describe the solution you'd like**
Some sort of implementation of M108: Cancel Heating (see https://www.reprap.org/wiki/G-code#M108:_Cancel_Heating) could work nicely. One concern is cancel heating during printing is problematic, as pointed out by the reprap wiki. However, a partial implementation that only allows cancellation during preheating would provide immediate impact without subjecting printers to potential harm.

**Comment by leptun** [comment]
Due to how we handle the command queue and serial commands at the moment, implementing something like M108 is close to impossible without a complete refactoring of the command parser. We'd need something similar to Marlin's Emergency parser feature.

As a workaround to this issue which will probably not be solved any time soon, you may try this octoprint plugin: https://plugins.octoprint.org/plugins/setandwait/. I've used it for a few months and I didn't have any issues with it when printing. Just keep in mind that the printer won't be aware that it is waiting for heaters, so the full menu structure would be available. Don't try to do anything risky with the firmware while octoprint waits for the target temperature.
With this plugin you can cancel heatup immediately and start another print without waiting.
