### ISSUE TITLE
[BUG] Restart after SD removal

### ISSUE THREAD

**Issue by KOBALT3D** [prusa3d/Prusa-Firmware#3244]
**Printer type** - [ MK3S ]
**Printer firmware version**-  [ 3.10.0 ]

**SD card or USB/Octoprint**
  No Octoprint 

**Describe the bug**
  After removing SD card from slot and selecting _No SD card_ from Main Menu printer restarts. Before restart the menu item _Main_ is displayed and after secont or two a backslash is diplayed on th second line
  
**To Reproduce**
  1. Restart or turn on the printer without SD card inserted
  2. Insert SD card with files on it (I've not tested this with empty SD card) 
  3. After file list is displayed select _Back.._ to return to _Info Screen_
  4. Remove SD card
  5. Go to Main Menu and select  _No SD card_
  
**Expected behavior**
  No file list displayed if SD card is not present.
  
**Video**
  https://drive.google.com/file/d/1qfcaugxblDfEzYGYLuM48lr42mmoZO-y/view?usp=sharing

**Comment by gudnimg** [comment]
I am unable to reproduce this. I have MK3S+ though not sure if the difference is large there.

Edit:

I am seeing a different behaviour when I open the "No SD card" submenu when:

1. No SD card on boot (Here I see a little folder icon with two dots on the second line)
2. Card is removed after boot (second line is empty)

I think the folder icon I am seeing is due to this line: https://github.com/prusa3d/Prusa-Firmware/blob/1279a6cf4b852287ba708ea7f76c7ebb49f80c1c/Firmware/ultralcd.cpp#L7247

This seems kind of redundant to me since the top line "Menu" is a back button.

**Comment by gudnimg** [comment]
@KOBALT3D It is strange in the video that it prints a backslash before the restart. `"/"` maybe that's a hint? 🤔 I've never seen a backslash on my end (at least I don't think so).

**Comment by DRracer** [comment]
@KOBALT3D please try the latest FW 3.10.1-RC1 and report back if your issue persist.
Btw. we are also unable to reproduce your issue on multiple machines.

**Comment by KOBALT3D** [comment]
SOLVED - Factory Reset - Erase All
