### ISSUE TITLE
  [ENHANCEMENT] Request confirmation if gcode specifies temperature for different filament than last loaded

### ISSUE THREAD

**Issue by uzytkownik** [prusa3d/Prusa-Firmware#3260]
Please, before you create a new feature request, please make sure you searched in open and closed issues and couldn't find anything that matches.

Enter what type of printer or upgrade the enhancement applies to.
**Printer type** - MK3S but applies to all
**MMU Upgrade** - No upgrade but applies to all

**Is your enhancement related to a problem? Please describe.**
I wanted to print enclosure so I was about to print door knob. However I haven't notice that gcode on the page was for PEG not PLA. I aborted in before nozzle heated above temperature for PLA.
  
**Describe the solution you'd like**
Last used or loaded filament should be stored in firmware and if gcode differs it should ask user for confirmation. This may be important for new users who may not notice it in time and when the temperatures of the filament are very different.

**Comment by wavexx** [comment]
That would be nice to have indeed. I also had this several times, despite being experienced. You might either forget to set the correct material in while slicing (last used material - my most common mistake), or forgot to unload.

Extending M862 to include a "filament check" based on the slicer's "filament type" (the property you set in Filament -> Advanced) would make a lot of sense.

Storing a short character sequence (say, 6 chars) for the last used material type is also doable.

The tricky part is how to improve the load/unload filament preload code so that when you preheat "PLA", it *also* sets the material type to PLA. But you cannot rely on this, because the preheat list in the printer is *not* exhaustive (for odd materials, I choose the closest temps by hand), so you might still have cases where starting a new print with a new material type should ask for manual yes/no confirmation *and* set the new type from then on.
