### ISSUE TITLE
Prusa Slicer - MMU2S extruder print order

### ISSUE THREAD

**Issue by Ecapox** [prusa3d/Prusa-Firmware#3347]
Would like the ability to select the extruder printing order when using the MMU2S.

I keep the my list used colors in the followinf order:

Extruder 1 - black
Extruder 2 - gray
Extruder 3 - red
Extruder 4 - white
Extruder 5 - misc

When printing an object that is black with red letters on the first layer, it currently prints the black color first and then the red color second. I'd like it to print the red first then the black (extruder 3 then extruder 1). 

I know I can move the filament around if i want red printed first but the ability to determine order would be a great improvement.

**Comment by gudnimg** [comment]
IMO this feature request should be solved on the PrusaSlicer side rather than via firmware.

Say we did implement this. How would the firmware know when to use your proposed order vs the order chosen by the slicer? I don’t know how the Slicer decides the order, and I would think it is up to the Slicer and not firmware.
