### ISSUE TITLE
  [ENHANCEMENT] Add 'Yes' and 'No' choices to message: "G-code sliced for a different printer type. Continue?"

### ISSUE THREAD

**Issue by gudnimg** [prusa3d/Prusa-Firmware#3421]
**Printer type** - MK3S
**MMU Upgrade** - MMU2S

**Is your enhancement related to a problem? Please describe.**
If a print is started which was sliced for only the MK3S ( and no MMU) but the actual printer has an MMU, then this message will pop up.

![274117257_308470794598305_2504019683744679818_n](https://user-images.githubusercontent.com/8218499/154851614-f2b35d67-a997-4818-aa1b-c06cdf60bf35.jpg)

  
**Describe the solution you'd like**
I would like to see a "Yes" and "No" choices. Right now it feels like I don't have a choice because when I click the knob, the printer just continues with the print.

**Comment by gudnimg** [comment]
This seems to work but is kinda wonky user experience. I would not consider this an acceptable solution.
<img width="731" alt="image" src="https://user-images.githubusercontent.com/8218499/154853626-ee085ad1-e5b6-4e9d-85d3-ae272945a682.png">

The `Yes` and `No` options don't appear at the same time as the message. And while the print is stopping after selecting `No` option the LCD stays blank until done. With the MMU it takes a few seconds since the printer will pull the filament all the way back up to the FINDA sensor. It is weird to me to see the LCD blank for too long :)

Side note... after booting up the printer I proceeded to select a file from the SD card to print, the message did not appear this time. The printer proceeded to heat up without any issues. It wasn't until I loaded a filament to the nozzle through the LCD that this message appears (after I selected a file to print). 🤔 

I will not spend more time on this today, may visit it again later.

**Comment by leptun** [comment]
The printer identified itself as MK3S until the MMU connects, after which it identifies as MK3S_MMU2S. You started the print so quickly that the MMU did not have time to connect. That's why you didn't get the message in that scenario. Luckily, I've got a fix for this in the new MMU2 implementation, so we can ignore that issue for now.
I was also thinking of doing something similar like you did above, but as you said that approach didn't really work. We will investigate this at a later time. Not a critical bug. Just some mild inconvenience.

**Comment by gudnimg** [comment]
This issue can be solved with `lcd_show_fullscreen_message_yes_no_and_wait_P` after this PR is merged: https://github.com/prusa3d/Prusa-Firmware/pull/3090

It was a mistake on my part to use `lcd_show_multiscreen_message_yes_no_and_wait_P`
