### ISSUE TITLE
[BUG] Doesn't re-home after crash detection pause when carriage blocked

### ISSUE THREAD

**Issue by ulope** [prusa3d/Prusa-Firmware#3460]
**Printer type** - MK3
**Printer firmware version** -  3.10

**MMU upgrade** - N/A
**MMU upgrade firmware version** - N/A

**SD card or USB/Octoprint**
USB/Octoprint

**Describe the bug**
When the crash detection pause triggers while the hotend carriage is blocked from moving (e.g. filament tangle) it doesn't re-home X/Y after the user has selected continue print leading to printing in midair.
 
**To Reproduce**
- Print anything
- Simulate a filament tangle (e.g. force the hotend to the left and prevent it from moving)
- Repeat until the "Crash detected. Resume print?" message is shown.
- Select "Yes"
- Note that no re-homing is preformed
- Printing resumes in a random location
  
**Expected behavior**
The printer should re-home X/Y after resuming from a crash pause since it can't be sure homing succeeded before the pause.
  
**G-code**
Anything will do, here's a cylinder: [Shape-Cylinder_0.2mm_PETG_MK3_12m.gcode.zip](https://github.com/prusa3d/Prusa-Firmware/files/8410184/Shape-Cylinder_0.2mm_PETG_MK3_12m.gcode.zip)

**Video**
[Video example](https://www.youtube.com/shorts/xBTIq-TB_So) (if you want to skip me torturing the printer, skip to ~20s)

**Comment by Prusa-Support** [comment]
Thanks for reporting.
Apparently, this is not a firmware bug but a case that deserves proper troubleshooting.
I see how a firmware enhancement could help though.

The crash detection is triggered correctly, the XY-homing is performed as expected (not correctly due to external factors) and the print is paused as expected after a few subsequent crashes (three I believe).
The XY-homing was run before prompting the message of resuming the print, as expected, but something prevented the correct XY-homing on the X-axis (in fact the Y-axis was able to move freely and moved to the correct position).

Probably what happened is that the "tangled filament" prevented the correct homing (wrong position or soft homing), and when the "tangled filament problem" was resolved it was already too late because the XY-homing was performed already before the crash-pause.

So the tangled filament was the problem in the first place - a case of troubleshooting, but, as an enhancement, what could have helped in this case, is pausing before XY-homing, so that the XY-homing can be performed only after resolving the problem.

Michele Mormarco
Prusa Research

**Comment by ulope** [comment]
Yes true, it's not a bug in the firmware per-se but it's still incorrect behaviour of the combined firmware-hardware system.

**Comment by Prusa-Support** [comment]
In that case, the issue will remain open, as it may be an opportunity for our developers and contributors to improve the firmware.
Thank you again for your feedback.

Michele Mormarco
Prusa Research

**Comment by SteveBaum** [comment]
I have the same issues as ulope with firmware 3.11 on my Prusa MK3 S. A crash is very often detected and afterwards there is no return to home and the x-position is entirely lost.

**Comment by Morgan-T-fr** [comment]
Hi, 
same issue ( firmware 3.13.0-6873) on my Prusa MK3S+. 
A crash  is detected and after  : home begin  ok on Y but not X  ( nothin physically block nozzle to home)
so print resume base on bad X and go of plate

rq : print  mode : **Complete individual  objects** ( sequential printing)

**Comment by ulope** [comment]
Not solved

**Comment by ulope** [comment]
Still not solved.

And stale bots are the worst.

**Comment by 3d-gussner** [comment]
@ulope Using stale bots have dis- and advantages. I watched you video and this is a very aggressive way you simulate a crash.
I just tested this with the MK404 simulator and latest build (upcoming FW 3.14.0).
- After a crash the printer tries to recover from crash
- After few attempts the printer asks to recover from, at this point you should only answer with Yes to continue when cleared any potential issue.
- After solving the issue, when I select Yes to continue the printer DOES home XY and then continues the print.
