### ISSUE TITLE
[BUG]3.12.0-BETA1 Firmware doesn't detect filament sensor

### ISSUE THREAD

**Issue by Build-a-Skill** [prusa3d/Prusa-Firmware#3649]
MK3s 

I wanted to try out the new 3.12.0 Beta firmware on an older mk3s(late 2019... i think). After flashing, it couldn't detect the filament sensor. I reverted back to 3.11.0 and it works fine.

**Comment by leptun** [comment]
Can you please upload a video of it not working? Also, are you sure it's MK3S and not MK3? They use different sensors and are not compatible (need different firmware files).

Also, which IR sensor revision is shown in the Support menu (that is if the correct firmware was installed)

**Comment by hoak** [comment]
Well for me 3.11.0 doesn't detect the filament sensor so I had to revert back to 3.10.0 so this is a larger issue.

I have two MK3S+ printers and both upgraded to 3.11.0 at the same time, both could not detect the filament sensor, and both reverted back to 3.10.0 and could then detect it no problem. So this issue is larger than the current beta version. One of the printers was brand new kit from a year or so ago and the other has been continuously upgraded since 2018 with the newest upgrade parts. Both printers are working flawlessly at 3.10.0 now. I am scared to try any new firmware until this gets fixed.

**Comment by Prusa-Support** [comment]
Thanks for reaching us.

We can't reproduce this issue, and we can't exclude the matter of firmware-vs-design incompatibility.
We would appreciate some evidence, like the video requested above.

A troubleshooting session via the official support channel could help remove doubts about compatibility.
https://help.prusa3d.com/article/customer-support_2287

Michele Moramarco
Prusa Research
