### ISSUE TITLE
[FEATURE REQUEST] Synch bed and nozzle heating

### ISSUE THREAD

**Issue by KilianB** [prusa3d/Prusa-Firmware#3735]
**Is your feature request related to a problem? Please describe.**

When printing with a high print bed temperature heating up the bed usually takes a lot longer than heating up the nozzle. During this period filament might start to ooze from the nozzle and some types of filaments loose their properties if exposed to high temperature for an extended period of time.

Here is an example with ASA where the nozzle hit 260° and is sitting idle for a few minutes until the bed reached its target temperature.

![image](https://user-images.githubusercontent.com/9025925/200117876-eb1ff41f-2364-409e-8777-82bdf571c9e5.png)

**Describe the solution you'd like**

The hotend and bed should reach their maximum temperature at roughly the same time.

**Describe how it would work**

With the new temperature calibration feature rolled out in the current beta firmware we are aware of expected temperature profiles for a printer. Using this we could defer heating either the bed or nozzle until the appropriate point in time.

A more trivial approach would be to gradually increase or decrease the power of the heating element depending on the temp delta.

Ref: https://github.com/prusa3d/PrusaSlicer/issues/9127

**Comment by adelyser** [comment]
Why would you implement this in firmware when you have the flexibility to make this happen in your start GCODE? Firmware shouldn't be overly complex to handle things that can easily be scripted from the slicer, IMHO. Here's how I handle it for no-ooze....

```
M104 S160 ; set extruder temp to pre-heat
M190 S[first_layer_bed_temperature] ; wait for bed temp

G28 W ; home all without mesh bed level
G80 ; mesh bed leveling

M109 S[first_layer_temperature] ; wait for extruder temp
```

**Comment by KilianB** [comment]
Maybe the issue should be moved back to the slicer. I just feel that it is a reasonable default and the firmware can be a bit smarter about it than just playing around with the heating order.

**Comment by Prusa-Support** [comment]
Thank you for sharing your idea.

I find it reasonable to keep the preheating process as simple as it is now, so the nozzle can ooze a little before the start of the print, otherwise it may slightly ooze during the initial calibration.

The little void in the nozzle created by oozing will be compensated for, during the "intro purge line", where also the plastic (possibly mildly degraded by heat) is purged.

In other words, the suggested idea may not necessarily be beneficial. It may seem to be a personal preference at this point, and Prusa Slicer would allow individuals to set up a custom start g-code.
For example, one can heat up the bed first, and also set a "wait" via `G4` code before start heating the nozzle.

I recommend closing this issue. It can be re-opened in case of increased interest (maybe also moved in [prusa3d/PrusaSlicer](https://github.com/prusa3d/PrusaSlicer) repository if necessary).

Michele Moramarco
Prusa Research
