### ISSUE TITLE
ed temperature after unloading and loading the filament should be the same as set in the gcode for given file.

### ISSUE THREAD

**Issue by Valthol** [prusa3d/Prusa-Firmware#3875]
Is your feature request related to a problem? Please describe.
I am printing PLA with bed temperature of 40C and nozzle temp of 210C. When I unload the filament and load it back again the bed temp is set to default 60C(not a desired outcome) and nozzle temp stays at the temp given in printing gcode (this is desired outcome).

The bed temperature should behave exacly like the nozzle - it should be set as given in gcode before unloading.

First - it wastes time, because often I have to wait for bed to get the right unload/load temperature, which I don't exacly need
Second - if you do this multiple times a day with more than few printers - you always after you load the filament have to go to settings and change bed temp.

Describe the solution you'd like
It would be nice to have an option in the settings to keep given temperatures of filament after the load/unload procedure.

Is there is any option to hard change it in the firmware for now, waiting for possible feature added in future?

**Comment by Prusa-Support** [comment]
Thanks for reporting.
Indeed, the heatbed temperature doesn't need to be changed in any way.

The Pull Request https://github.com/prusa3d/Prusa-Firmware/pull/2335 improves this behavior. It was recently merged and I'm not sure whether it will definitely come out in the next release or in a few.
On a side note, this PR improves the general un/load process so I can't be sure if it will apply in the specific scenario described in this issue.

The issue can stay open until the Pull Request definitely gets into effect for us to check.
All in all, I think it was worth a mention in order to link this issue to that PR, as this is probably already "in progress".

Michele Moramarco
Prusa Research
