### ISSUE TITLE
[BUG] Clear TM error acknowledgement doesn't allow to calibrate the thermal model

### ISSUE THREAD

**Issue by gregsaun** [prusa3d/Prusa-Firmware#3890]
**Printer type** - Prusa MK3S+ with Bear customs and E3D Revo Micro hotend
**Printer firmware version** - 3.12.0 Final
**MMU upgrade** - None

**Describe the bug**
I am unable to calibrate the thermal model for a safer hotend like the E3D Revo. Clear TM error acknowledgement seems to only unlock the LCD standard menu but doesn't allow to calibrate the thermal model. The documentation says:

> Added Clear TM error
> 
> To “unlock” the printer in case a “Thermal anomaly” is detected, there is a new option in the menu LCD menu -> Clear TM error to temporarily clear/acknowledge the issue. As this is only a “temporary” solution proper calibration is recommended. In case the temp model calibration doesn't solve this, please contact Prusa support or open a [GitHub issue](https://github.com/prusa3d/Prusa-Firmware/issues/new/choose).
  
**To Reproduce**
1. Flash the 3.12.0 firmware
2. Follow the Thermal Model calibration wizard => raise the THERMAL ANOMALY error
3. LCD menu -> Clear TM error
4. LCD menu -> calibration -> Temp Model cal. => raise the THERMAL ANOMALY error
  
**Expected behavior**
From the LCD menu we should be able to calibrate the thermal model for modifications on the hotend/extruder (new extruder body, new hotend, adding a sock) as well as the use of a safer hotend like E3D Revo. The release notes are not clear enough on how to proceed in such case.

**Comment by arekm** [comment]
TM is incompatible with Revo at this moment (see https://github.com/prusa3d/Prusa-Firmware/issues/3636). If you want to use this firmware with Revo then you need to disable TM.

You can do that using serial console and issuing M310 S0 followed by M500.

There is no menu for this (due to: "We removed that option from the menu (we want to prevent ordinary users from disabling the TM easily/accidentally)").

Unfortunately that M310 S0/M500 doesn't seem to survive firmware upgrades (RC2->final upgrade and TM wizard came up again on first boot), so needs to be repeated after each upgrade. (Added https://github.com/prusa3d/Prusa-Firmware/issues/3891 for this)

**Comment by gregsaun** [comment]
Thank you for your answer.

I am aware of #3636 and I have reported my data over there. The release notes was unclear to me and I understood that the Clear TM error allow us to calibrate the thermal model afterward, might be good to make it clear that this acknowledgement is not working in the case of the Revo.

As safety is a difficult and important topic, could you please help me to clarify some extra points:

1. My understanding is that `M300 S0` will disable the new TM, could you confirm that we are back to the same safety features as in the previous firmware versions?

2. In #3636 we could have a successful TM calibration using the command `M310 A F0`. If we do this, will the new TM safety features works the same way as it should with an Original Prusa extruder and hotend?

**Comment by arekm** [comment]
1. AFAIK only disables new TM feature and all old thermal checks still work.
2. From source code "`F` - force model self-test state (0=off 1=on) during autotune using current values". Looks like this disables TM anyway.

But I'm only a printer user, so lets wait for devs/support comment.

**Comment by gregsaun** [comment]
Thanks for your help!

I will wait a solid answer from the dev team :)

**Comment by wavexx** [comment]
The wording in the release notes are a bit unclear.

"Clear TM error" just acknowledges the error. The idea is that when a TM error is triggered, the only way to recover is to go to the printer, check what's wrong, and physically use the LCD. For example, if you're printing via serial/octoprint, a TM error will issue an instant pause: you cannot "unlock" the printer remotely. This is done intentionally so that a host (prusalink/octoprint or anything) can't accidentally send more print commands and/or run a "pause" sequence in such a condition, since the pause sequence will often include commands to change the nozzle temperature.

When you're in front of the printer, and you have a live print, you normally can STOP/RESUME. This implicitly acks the error and the printer will resume to full functionality. However, if there was no print going on, the printer will stick auto-lock. Since you don't have STOP/RESUME in that case we had to add an extra menu item (see #3630).

> My understanding is that M300 S0 will disable the new TM, could you confirm that we are back to the same safety features as in the previous firmware versions?

Absolutely yes. You can't disable the previous safety features. The aim is to also make it hard to disable TM for the same reason, but we know it doesn't work on *everything* just yet.

> Unfortunately that M310 S0/M500 doesn't seem to survive firmware upgrades (RC2->final upgrade and TM wizard came up again on first boot), so needs to be repeated after each upgrade.

This is because RC2 still didn't have an enforced calibration workflow as part of the wizard. This shouldn't be the case for all future versions.

**Comment by gregsaun** [comment]
Thanks @wavexx , I now understand the purpose of Clear TM error and it makes sense.

> Absolutely yes. You can't disable the previous safety features. The aim is to also make it hard to disable TM for the same reason, but we know it doesn't work on everything just yet.

Perfect thanks 👍 

May I ask you to also answer my second point?
_2. In #3636 we could have a successful TM calibration using the command `M310 A F0`. If we do this, will the new TM safety features works the same way as it should with an Original Prusa extruder and hotend?_

**Comment by wavexx** [comment]
> In https://github.com/prusa3d/Prusa-Firmware/issues/3636 we could have a successful TM calibration using the command M310 A F0. If we do this, will the new TM safety features works the same way as it should with an Original Prusa extruder and hotend?

Unfortunately not. `M310 A` (or `M310 A F0`, since 0 is the default) just runs the calibration by itself. It will work on also on the revo, but the checking part will still fail.

`M310 A F1` is yet another defense in-depth against hardware problems and runs the checker as the calibration is running.

When running the calibration we're effectively heating, and while unlikely, there is the potential to get a hardware failure right at that moment. `M310 A F1` effectively instructs the autotune to keep checking the hotend while calibrating using the previously stored values. In the variant files we pre-populated an average of the stock values, so that even right after a full reset you can *always* keep the safety active without ever disabling it.

**Comment by gregsaun** [comment]
@wavexx thanks for the info. Yes it makes sense for the potential hardware failure during calibration. To be sure I understand correctly, the `M310 A F1` is the command used by the LCD menu used calibrate the TM?

**Comment by wavexx** [comment]
> I understand correctly, the M310 A F1 is the command used by the LCD menu used calibrate the TM?

Yes (and also during the wizard)

**Comment by gregsaun** [comment]
Okay so if I summary it correctly, for the E3D Revo hotend there is no way to use this new thermal model. We can use the `M310 A F0` to clear up error messages but the new thermal model will not be used. This means it will not react to a wet cotton tip on the nozzle after the `M310 A F0` calibration process, am I understanding this correctly? The old safety features are still there and a thermal runaway will be kicked if needed.

**Comment by wavexx** [comment]
All correct. It's a bummer the current model as it is doesn't work for the revo (I was hoping the PTC didn't make enough difference to matter in order to keep everything simpler), but there's no loss in safety compared to the previous behavior.

As an extra detail, pretty much all resistors have a positive temperature coefficient (meaning that the current->heat conversion is not truly perfect and keeps getting worse as we increase the temperature due to various losses). Calibrating this new coefficient will probably also improve the tracking on regular heaters as well, meaning that maybe we could have a bigger warning->error window.

**Comment by gregsaun** [comment]
Thanks for confirming everything, I understand it fully now. The Revo is very different from a V6, probably using a PTC in a V6 wouldn't make such a difference. Some key points of the Revo:
- The hot block is very small so it gets hot crazy fast
- The hot block is a ceramic heater with metal in the middle, very different than the V6 alu block
- The thermistor is molten inside the hot block and much closer to the heating element (closer to heating element than the nozzle)
- The shape of the nozzle is also very different, more mass to heat up and bi-metallic heatbreak
- In my case; I use the Revo Micro version (not Revo Six) and the hotend cooling is more efficient (sharper transition in the break)

**Comment by Prusa-Support** [comment]
> **Set the calibration state when running M310 A (MK3/MK3S/MK3S+)**
Calibrating the Thermal model using the G-code command M310 A F0 didn’t set the TM calibration state correctly. This is now fixed and calibration is stored as expected.
Kudos to our community members @arekm, @FrHePo and @gregsaun for reporting this https://github.com/prusa3d/Prusa-Firmware/issues/3890.

https://github.com/prusa3d/Prusa-Firmware/releases/tag/v3.12.1

I hope you don't mind me closing this issue as solved. However, please feel free to share further feedback on this thread.

Michele Moramarco
Prusa Research
