### ISSUE TITLE
[BUG]Calibration Wizard Yes means No, No means Yes

### ISSUE THREAD

**Issue by bogamol** [prusa3d/Prusa-Firmware#3945]
**Printer type** - MK3S+
**Printer firmware version** - 3.12.0
**SD card or USB/Octoprint** Octoprint 
  Please let us know if you print via SD card or USB/Octoprint

**Describe the bug**
Mismatch in the options for starting the calibration wizard once it has already been done.

If you press Yes to continue it does not continue, but if you press no to not continue it continues.
  
**To Reproduce**
Go to Calibration -> Wizard ->

'Hi, I am your Original Prusa i3 Printer. Would you like me o guide you through the setup process?

Yes No

**Expected behavior**
If you select yes to continue it should start the calibration process. If you press no, it should drop out of the calibration process and go back to the main menu.
  
However, the opposite happens. If I press yes to continue, it bumps you back to the main menu, and if you press no it continues the calibration process.

**Comment by 3d-gussner** [comment]
@bogamol Thanks for the report, we already have this fixed in [PR3934](https://github.com/prusa3d/Prusa-Firmware/pull/3934/files#diff-5fbfdca43c192573e31d8e78d255c510fb6e213b118cf38173277ec2a2163880R3974)
The new release has this fix https://github.com/prusa3d/Prusa-Firmware/releases/tag/v3.12.1
Please consider to close this issue.
