### ISSUE TITLE
FW crash if pausing when filament change (MMU)

### ISSUE THREAD

**Issue by Ro3Deee** [prusa3d/Prusa-Firmware#3990]
**Printer type** - MK3S
**Printer firmware version** -  3.12.1

**MMU upgrade** - MMU2S
**MMU upgrade firmware version**  - 1.0.6

**SD card or USB/Octoprint**
SD card

**Describe the bug**
  Prusa FW crashed if you pause when filament is changing. After crashing, the printer informs that I can resume the printing, but their is no option to resume.
  
**To Reproduce**
 1. start a multi material print
 2. when the first filament finished printing and is unloaded from the nozzle, just before the selector of MMU is about to move to the next filament, pause the print. The FW wil crash.
  
**Expected behavior**
- no crash
- option to resume printing
  
**G-code**
[MMU-Tip_5colors-GCode.zip](https://github.com/prusa3d/Prusa-Firmware/files/10660531/MMU-Tip_5colors-GCode.zip)

**Video**
It happen every time, no matter the gcode. I can post a video, on request.

**Comment by Ro3Deee** [comment]
I tested on 3.11.0.: if i pause during filement unload, it doesn't crash. It pauses the print, the print head moves to the back (the plate moves forward), then the filament continues changing, it loads the next filament and the printer waits for the user to resume printing.

So it a bug of  3.12.1

**Comment by gudnimg** [comment]
Just want to reply and let you know that we're aware of this issue and it's listed as a known issue in the release notes.

**Comment by mcfada** [comment]
> Just want to reply and let you know that we're aware of this issue and it's listed as a known issue in the release notes.

I would like to add this has happened to me on last 2 tries while not issuing a pause command (though there is a pause much later in the gcode). Printer freezes during a color change on the purge tower, cools down and sticks the nozzle to it. Screen says “FW crashed. You can continue printing” then you click and can’t continue anything. No flashing lights on mmu2 s, but the filament indicator is on the wrong filament. Should I install an older FW to get thru a full color print? FW for the printer or the MMU2?

**Comment by gudnimg** [comment]
Minor update.... been looking into this problem this morning and I found a fix on my end (just need to verify my fix is actually correct) The issue looks like a Watchdog timeout.

**Comment by gudnimg** [comment]
For reference only.... this is what the logs look like when I:

1) start a multicolor print
2) Pause the print on the first load (where we would expect the purge line)

3.11 print pauses correctly and the extruder is parked
![image](https://user-images.githubusercontent.com/8218499/218308974-be23d028-8738-4381-9754-5cfd5b988692.png)

3.12.1 print attempts to pause but crashes due to watchdog timeout. I suspect we are not returning to the top-level `loop()` somehow. Adding a simple watchdog kick in `mmu_get_response()` does not resolve the issue fully (only solves the FW crash)

Even if I fix the watchdog problem locally, the extruder is still not parked for some reason.

![image](https://user-images.githubusercontent.com/8218499/218308993-540d21d2-8af2-4236-980f-70f4aad21644.png)

**Comment by gudnimg** [comment]
Adding this to the 3.13 Milestone, I think this issue should be closed once FW 3.13 is released.

**Comment by gudnimg** [comment]
Closing as this is now resolved with FW 3.13.0 and MMU FW 3.0.0 :)
