### ISSUE TITLE
[ENHANCEMENT] Thermal Model Protection should accept 30W to 60W heaters

### ISSUE THREAD

**Issue by knightsljx** [prusa3d/Prusa-Firmware#4015]
This suggestion is tangentially related to issue #3636 but on a broader spectrum.

The current allowable range of the thermal model protection is too narrow to accommodate the most common 24V heater cartridges on the market. Even E3D themselves sell 24V 30W heaters. It should not be on the user to expect to know what is happening, especially when all other printers on the market simply need a PID tune to get the common heaters working.

A better implementation of the Thermal Model Protection should allow a broader range of heater wattages/resistance to accommodate common models. I believe 25-65W should be an ok range inside the software to account for manufacturing tolerances. Thank you.

**Comment by knightsljx** [comment]
I just found out that volcano hotends go up to 80W, so the range of accepted heaters need to go up for thermal model protection

**Comment by darraghbr** [comment]
According to the docs M310 accepts a 'P' term which is the power in watts, but from what I can see the documentation does not suggest an allowable range? Is there a finite range that is just not documented?

**Comment by knightsljx** [comment]
Regular customers should not have to go into the GCode. Thermal model protection calibration should work just like PID tuning. It fits itself to whatever is currently installed

**Comment by Prusa-Support** [comment]
Thanks for reaching us.

Our suggestion for regular customers is to use genuine Prusa stock parts.
Advanced users modifying the printer in any way, or users using any third-party components, should do that at their own risk.

About the thermal model calibration for other heaters, using a different wattage than the default.
>If you know the power of your heater (for example if you’re using a more powerful heater) you must set the correct value with M310 P<power in watts> and only then recalibrate the model. 

Please find more about the thermal model functionality and parameters in the relevant Pull Request https://github.com/prusa3d/Prusa-Firmware/pull/3552.

If the calibration will fail after the parameters tuning, please consider creating a log file as explained at https://github.com/prusa3d/Prusa-Firmware/issues/3636#issuecomment-1262926997, and upload it in the thread. It may be of use for our developers to understand the problem or for further future improvements.
Also, because we are not looking at stock parts, please provide precise information about your printer's hardware.

Meantime, you can disable the thermal calibration by running two simple codes (`M310 S0` followed by `M500`) via Pronterface or similar programs, and "normally" use the printer without the thermal model.

Michele Moramarco
Prusa Research

**Comment by Prusa-Support** [comment]
Is this issue still relevant?
If so, please provide thermal calibration logs and all hardware details.

Michele Moramarco
Prusa Research

**Comment by Prusa-Support** [comment]
This issue will be closed as stale. However, we would still appreciate feedback and - most importantly - logs.

Michele Moramarco
Prusa Research
