### ISSUE TITLE
[QUESTION]<Is there a MBL fade off height?>

### ISSUE THREAD

**Issue by vkojchevski** [prusa3d/Prusa-Firmware#4106]
I was wondering if there is a MBL fade off height and if so, what height is it set at. I found this https://github.com/prusa3d/Prusa-Firmware/issues/1717 marked as resolved, but I wasnt able to find a definitive answer if was implemented, even after trying to search the firmware code, though I admit I am not that code savvy, I just tried searching for FADE_HEIGHT. I would kindly ask for some insight.

**Comment by Prusa-Support** [comment]
Thanks for bringing this back to our attention.

Indeed the feature was eventually not implemented due to minor firmware incompatibility problems, but the developers wouldn't mind reopening issue #1717 and looking into this.

As a recap, to answer your question, no it is not implemented yet and issue #1717 will be reopened now.

If this adequately addresses your answer, please close this issue.

Michele Moramarco
Prusa Research

**Comment by Prusa-Support** [comment]
It seems safe to close this issue now.

Michele Moramarco
Prusa Research
