### ISSUE TITLE
3.12.2 Not detecting blob of death with thermal model protection ON (and layer shift too)

### ISSUE THREAD

**Issue by Ethan-Ming** [prusa3d/Prusa-Firmware#4142]
running stock MK3S+ printer, printing was fine on 3.11
Since we upgraded to 3.12 two days later  blob of death appeared, so i cleaned nozzle and did a re-calibration of PID & thermal model
Aand here this black guy again! (2nd time)
<img width="596" alt="image" src="https://user-images.githubusercontent.com/36059080/231763285-f711d917-702c-43d2-88b8-75c674df7813.png">

I don't know if 3.12.2 is just not detecting it or actually CAUSING it, but evidently the detection part definitely not working as expected. 
will downgrade to 3.12.0 see what happens

as for the layer shift:
 i forget to took picture so you just have to take my word for it, I had a failed print with X shifted to the right and crash detection did not pick it up (normal power mode), i checked the belt tension afterwards and it was in optimum range

**Comment by Prusa-Support** [comment]
Thanks for reaching out to us.

The purpose of the Thermal Model Protection is more precise temperature management, hence faster and more accurate detection of thermal-related issues.
Ultimately, the feature is not designed to detect blobs.
A thermal anomaly may be triggered by blobs only if the blob causes a discrepancy between the temperature graph and the "expected model". A blob could be indirectly detected if the blob causes thermal anomalies, and this could be called a collateral effect of the feature, not an intended result.

The axis collision will be detected if an obstacle is on the way and opposes the movement.
If nothing opposes the stepper movement, no crash will be detected.
For example, if the motor pulley gets loose, the motor will spin almost frictionless, no matter if the axis doesn't move correctly: the layer shift will occur but the motor won't be subject to increased friction or blockage.
Another example could be that the extruder is hit and pushed in the direction of the current movement: if the push amplifies the motor's movement no friction or blockage will be detected - the axis friction against the motor will be relieved instead.
Not sure if any of these cases apply here, these are just examples.

The layer shift is closely related to the cause of the blob indeed.
The blob can't be caused by the firmware. A blob could most likely be related to print preparation or hardware problems.
This may seem an unfortunate coincidence and the issue will supposedly persist with any other firmware version. I'm sorry for the accident.

These articles may help.
https://help.prusa3d.com/article/layer-shifting_2020
https://help.prusa3d.com/article/extruder-blob_2005

Michele Moramarco
Prusa Research

**Comment by Prusa-Support** [comment]
This issue doesn't apply to the feature and should therefore be closed.
In fact, detecting blobs is not the purpose of this feature, but a collateral consequence observed in a few cases - where the printer is properly calibrated printers and the environment temperature is adequately controlled.

However, your feedback is most valuable to us. Thank you.

Michele Moramarco
Prusa Research
