### ISSUE TITLE
[BUG] Remaining time not reset in First layer Calibration

### ISSUE THREAD

**Issue by feress737** [prusa3d/Prusa-Firmware#4171]
Printer: MK3S+
Firmware: 3.12.2

The remaining time will not be reset if you perform the First Layer Calibration several times in a row. The time adds up.

**Comment by gudnimg** [comment]
I can see the time you are talking about. It's not reset in 3.13 either.

It looks like to me this meant to show how much time has passed since the calibration started, and not the time remaining. The time is also not added to your printer's statistics (for total print time).

See https://github.com/prusa3d/Prusa-Firmware/blob/a354aad7621f47d42aa3e13b49991129e1f86384/Firmware/ultralcd.cpp#L490 this is the number being shown on the LCD. It increases with time passed.
