### ISSUE TITLE
[FEATURE REQUEST] Upgrade firmware from SD card

### ISSUE THREAD

**Issue by dan21dan** [prusa3d/Prusa-Firmware#4247]
**Printer type** - MK3S

**Is your feature request related to a problem? Please describe.**
To update the firmware, I have to bring the computer to the printer or the printer to the computer, which I find very unnecessary just to upload the new firmware file.
  
**Describe the solution you'd like**
Allow firmware upgrade from a file stored on the SD card.

**Comment by vintagepc** [comment]
Unfortunately I don't think this is possible in a practical sense as  the current bootloader doesn't support it. Adding support would require adding quite a bit of code to the bootloader (SD card communication, FAT32 filesystem code) and I do not think it has the space for this. (And even if it did, I would imagine the risks of bricking a machine due to a failed bootloader update in the field would make it a non-starter)

See also #4068
