### ISSUE TITLE
[BUG]<Printer indefinitely ides if file started while loading filament>

### ISSUE THREAD

**Issue by valkires1** [prusa3d/Prusa-Firmware#4256]
**Printer type** -  MK3S+
**Printer firmware version** - 3.12.2-5713
**SD card**
  

**Describe the bug**
When you start a print file (from SD) while loading filament before it asks you did it load correctly it will just ideal at default temp (not at preset temps set in slicer) indefinitely and show print time counting up from when that happened.
  
**To Reproduce**
Insert new filament then immediately chose and select a new print file while it is still loading. You must select a file before it confirms the filament was loaded correctly. once you do, It will not ask you if it did and just indefinitely idle at default temp not at temp set on SD card.
  
**Expected behavior**
Should start printing once temps are achieved and filament loaded. Perhaps ask if filament was loaded correctly but not necessary since I started started the file while it was doing this, so clearly I don't care enough to wait around to for that to be a concern.
  
**G-code**
  N\A/don't have access to that

**Video**
  Here's a picture, video probably isn't necessary in this case; If you need more let me know.

![20230630_201027](https://github.com/prusa3d/Prusa-Firmware/assets/135301038/771950fa-8faf-4af0-bf71-fc7a9dc09554)

**Comment by wavexx** [comment]
This was likely as a result of #3564 (which is a fix for #2651). Starting an SD print while loading was taking place was previously broken. We now ensure that all filament actions (load/unload) are complete before the SD print can be started.

This is because starting an SD print is a special action as implemented in the LCD screen code: it doesn't "queue" the print to be started, but it actually starts it right away.

The reasoning is that if the filament is loading, and you start an SD print, the SD print cannot be just queued after the current move queue is complete. When you get the "color correct?" prompt, and you say "no", a new extruder move would need to be queued right in the middle of the current SD print.
