### ISSUE TITLE
BLtouch related code removed from firmware

### ISSUE THREAD

**Issue by jmtrappier** [prusa3d/Prusa-Firmware#427]
Need to be fixed, it is a really needed tool, better than PINDA if you want to print on glass.

Can we get a firmware version allowing us to use BLtouch, there is no reason to remove it.

**Comment by 3d-gussner** [comment]
@jmtrappier As Prusa is adding lot of features and try to make the use of the Prusa i3 MK2/s/MK3 simpler to users they needed to remove some Marlin code due to the ATmega 2560 controller.

At this moment the MK3 supports just 2 and not 5 languages (on the MK2/s) due to the ATmega 2560 limits.
They added an extra flash to the EINSY board to be able to offload some of the code, it isn't yet implemented but i am sure it will be with the final release.

Prusa has it's own Marlin fork and adjust it to their needs. They decided to go with the P.I.N.D.A probes and i don't (and we shouldn't) expect them to provide code for your/our mods to the original Prusa I3 MK2/s or MK3.

So if you need  BL-touch support go for Marlin or try to get the needed code in the Prusa-Firmware by your own. If you like some features from the Prusa fimware that are missing in Marlin you should try to get these in Marlin.

Lot of Marlin based firmwares are modified to the needs of the companies! 
Example: BCN3D has it's own fork for their BCN Sigmas
Some (Chinese) even don't provide (by Marlin opensource license) their code. Prusa Researc, BCN and other do!
