### ISSUE TITLE
Factory reset does not work on MMU3

### ISSUE THREAD

**Issue by Ro3Deee** [prusa3d/Prusa-Firmware#4287]
**Printer type** -  MK3S
**Printer firmware version** - 3.13.0

**MMU upgrade** - MMU2S
**MMU upgrade firmware version** - 3.0.0

**Describe the bug**
 In the MMU2 printed handbook, you can enter factory reset if you press the middle button and reset printer. 
In the [online version](https://help.prusa3d.com/article/factory-reset-mmu2s_1920) it says: Press and release the printer reset button. Immediately after releasing the X button, press the middle black button on the MMU unit and hold it. Release the button only when in the first LED position, both the green and the red LEDs are on, and at the same time, in the fifth LED position, the red LED is on.

This doesn't work on MMU3. The new handbook doesn't include a factory reset procedure. 
  
**To Reproduce**
  Press and release the printer reset button. Immediately after releasing the X button, press the middle black button on the MMU unit and hold it.
  
**Expected behavior**
  the first LED position, both the green and the red LEDs are on, and at the same time, in the fifth LED position, the red LED is on

**Workaround**
- Install 1.0.6 FW. Factory reset works now. 
- reset to factory settings
- install 3.0.0 FW

BTW. MMU3 FW source code is not available. MMU FW 3.0.0 source code is not published. On github, it is at 2.1.8: https://github.com/prusa3d/Prusa-Firmware-Buddy/tree/master/lib/Prusa-Firmware-MMU

**Comment by Julasch17** [comment]
this also does not work for me

**Comment by Prusa-Support** [comment]
Thanks for reporting, however, the factory reset instructions should still apply in the same way.

Please perform a factory reset to both, the printer (Einsy board) and the MMU module (MM-control board) before upgrading the firmware.
May the issue persist, please share a video of it.

Michele Moramarco
Prusa Research

**Comment by victorbjo** [comment]
The factory reset did not work for me either.

May I ask why you performed factory reset?
My MMU did not work after update and I had to downgrade FW to get it working.

**Comment by thomasloven** [comment]
I made a similar observation. MMU2S, firmware 3.0.0.
I had the homing problem in #4285 and tried to factory reset the MMU to solve it.

After solving the homing I came to think that maybe the reset problem was because the MMU couldn't start up completely when it couldn't home.
I also thought I needed to calibrate the bowden length, since I've been messing with the hardware a bit. So I tried the following:

- Press the X button.
- Immediately press and hold the middle button on the MMU.

This caused the homing problem to reappear, and I had to again send the `M708` command from #4285.
I.e. the MMU behaves as if factory reset just from entering the service menu?

I do not remember which LEDs (if any) were lit at that point. I was too surprised by the apparent reset.
Hesitant to try this again, but will do it if it can help and someone can tell me what to look for.

Possibly related; I also experience #4289.

**Comment by victorbjo** [comment]
@thomasloven 
I fixed my homing problem... Rather embarrassing but I needed to activate the MMU in the printer after the update, as per the release notes

**Comment by thomasloven** [comment]
Yes, but that issue goes on to discuss errors in the stall detection sensitivity, which is the problems I ran into.

**Comment by DRracer** [comment]
Please see: https://help.prusa3d.com/article/factory-reset-mmu_510075

**Comment by gudnimg** [comment]
Removing the bug label as factory reset works in the new MMU firmware. See comment above from @DRracer with documentation.

**Comment by Ro3Deee** [comment]
In the mmu2s manual, the reset procedure is:
![16908963779336424331241249983501](https://github.com/prusa3d/Prusa-Firmware/assets/124100239/0b300319-4bbc-4b23-be3a-75da69256b00)

The [new procedure](https://help.prusa3d.com/article/factory-reset-mmu_510075) is by holding the left side button and _reset the **mmu** unit_ by pushing the button on the right side of the MMU with an Allen key.

So we don't reset the printer, we should reset the mmu unit.

**Comment by gudnimg** [comment]
Correct 👍
