### ISSUE TITLE
MMU2S with MK3S+ Lights Not Working Switching Filament Slots

### ISSUE THREAD

**Issue by ljford7** [prusa3d/Prusa-Firmware#4289]
**Printer type:** MK3S+
**Printer firmware version:** 3.13.0
**MMU firmware version:** 3.0.0

**Describe the bug:** After upgrading the MMU2S to firmware 3.0.0, the lights don't light up when switching filament slots with the buttons on the MMU. 

**To Reproduce:** Manually switch slots on the MMU with the buttons on the MMU
 
**Expected behavior:** The lights should light up highlighting which slot is currently selected on the MMU

https://github.com/prusa3d/Prusa-Firmware/assets/2449331/70161835-0406-4f0c-bfc5-233a58846967

**Comment by StopJustStop** [comment]
I am also having this issue after upgrading the firmware.
MK3S+ with MMU2S - Printer is not modified with any 3rd party addons.  It's 100% factory.

When powering on the printer/MMU, the lights come on for a short time with the following pattern:

1.  Lights 1, 2, and 3 come on solid green.  Light 4 blinks slowly (both green and red) and light 5 blinks green quickly.
2.  Lights 4 and 5 go dark for a few seconds then same pattern:  Light 4 blinks slowly (both green and red) and light 5 blinks green quickly.
3.  All lights shut off
4.  Idler homes (and grinds like crazy for a moment).  I think it's the idler - the large cylinder with ball bearings.
5.  Selector homes (thing with PTFE tube attached)
6.  Lights remain off

After it finishes startup, the left button does move the selector left one space and the right button moves it right one space (just like before).  It just doesn't have any lights indicating which filament you have selected.  I also tried a factory reset on both the printer and the MMU2S.  The factory reset procedure does not seem to work on the MMU2S (there's already a bug report for that)

**Comment by DRracer** [comment]
Please see: https://help.prusa3d.com/article/status-led-explained-mmu3_510059

And no, LEDs do not reflect the position of the selector when moved.

**Comment by ljford7** [comment]
> Please see: https://help.prusa3d.com/article/status-led-explained-mmu3_510059
> 
> And no, LEDs do not reflect the position of the selector when moved.

This doesn't make sense. Why would a very useful function be removed from the new firmware?

**Comment by gudnimg** [comment]
Removed bug label for now because this behavior is by design in MMU FW 3.0.0.

**Comment by clintonefisher** [comment]
I have to agree with ljford7 - why would very useful functionality for LEDs that already exist be removed?  I don't mean to sound ungrateful, but what a waste of ten good LED indicators that are already numbered for each filament lane!   

I'm very curious as to the decision-making process behind this choice because it seems somewhat disrespectful to paying customers like myself who bought a MMU2S with the understanding that the LEDs were (obviously) for filament lane status.  Now, that obvious useful functionality has been removed, even though we paid $$$ for that functionality.

With competitors taking more and more of Prusa's business these days, it's good to keep long-time dedicated Prusa-fan customers happy by not removing already-paid-for functionality.  Thanks for listening, and thanks for all you do.

**Comment by Ro3Deee** [comment]
>  we paid $$$ for that functionality

@clintonefisher , you didn't pay for that "functionality", you paid for a device that switches filaments. 

I hated those leds. So no leds, no problems :)

But it would be nice that the leds indicate the current filament. It would be useful also for debugging to see if the MMU thinks it is on another slot than the selector/idler really (physically) are.

**Comment by StopJustStop** [comment]
> Please see: https://help.prusa3d.com/article/status-led-explained-mmu3_510059
> 
> And no, LEDs do not reflect the position of the selector when moved.

@DRracer @gudnimg    The MMU3 has a printed label on the front that shows the position of the selector.  If I had a MMU3, I would be fine with using the label to determine which filament was selected.  Please keep in mind that the MMU2S doesn't have the numbered slots printed on the front like the MMU3.  We can't look at a label and tell what position the selector is in.  For MMU2S owners, the ONLY indicator of selector position is the indicator LED.

The LEDs USED TO reflect the position of the selector.  That functionality has been taken away which just made it very painful for MMU2S users.

**Comment by Ro3Deee** [comment]
> Please keep in mind that the MMU2S doesn't have the numbered slots printed on the front like the MMU3.

You can print [this](https://www.printables.com/model/534292-mmu3-like-plate-with-customizable-logo-and-text-fo) with the MMU to have the numbered slots
https://www.printables.com/model/534292-mmu3-like-plate-with-customizable-logo-and-text-for-mmu2

**Comment by Prusa-Support** [comment]
Thank you for your feedback.

I'd like to ensure you that the meaning of LED lights is very different now.
This is intentional and the relevant [Help article](https://help.prusa3d.com/article/status-led-explained-mmu3_510059) was updated accordingly.
Feel free to go through it if you are curious to learn more about the meaning of the LED lights and please notice the lights no longer simply track the position of the "virtual MMU-extruder" or un/loading operations but provide further analytic information.

The user would not necessarily need to study the exact meaning of all light combos (information close to a machine language) but follow the indications on the printer's LCD displayed as messages (at a human language degree).

This is one of the biggest advantages of the new firmware.

The position of the selector is quite explicit and most importantly pretty much all operations can be performed via the LCD menu, now with an improved user interaction that doesn't simply rely on a combination of lights.

Michele Moramarco
Prusa Research

**Comment by clintonefisher** [comment]
That's neat that the new firmware uses the lights at bootup to show error status.  On my MMU2S they used to also show the selector location.  Some may not have liked the LEDs but I liked them and they were useful.  Now, this USEFUL functionality has been taken away.   Sure, I could abandon the wonderful new features of the new firmware, if I wanted the lights, but the point is WHY would Prusa remove a useful feature from long-standing customers?  

Feature removal is generally annoying to customers and you never know what action is the final straw that causes a long-time Prusa fan to jump ship for a competitor.

Why not make the selector LEDs an OPTION?   Put the option in a register accessible by GCODE.  Then EVERYONE is happy!  Old time MMU2S owners get the LED's.   MMU3 users who don't need them, or folks who don't like the LEDs, can turn them off.

Options are great ways to avoid annoying long-time customers and to keep them satisfied.

P.S.  If there's a legit reason for not keeping the original MMU2S LED behavior on the MMU2S with the new MMU3 firmware, like maybe you ran out of Program memory, or the LEDs took more power, I don't know, just tell us.  We'll understand.

**Comment by halofx** [comment]
> I'd like to ensure you that the meaning of LED lights is very different now. This is intentional and the relevant [Help article](https://help.prusa3d.com/article/status-led-explained-mmu3_510059) was updated accordingly. Feel free to go through it if you are curious to learn more about the meaning of the LED lights and please notice the lights no longer simply track the position of the "virtual MMU-extruder" or un/loading operations but provide further analytic information.

This doesn't justify a poor decision.
I agree with the annoyed folks, removing a useful function was a bad call. It is fine that the LEDs serve other functions while the MMU is going through other states, but why can't they still serve a function in the IDLE state? This seems very short sighted in my opinion.

**Comment by Ro3Deee** [comment]
It works for me _when printing_. MMU 3.0.0 fw. Here is a video:
https://youtu.be/z9jfaW7bJyQ

**Comment by halofx** [comment]
> It works for me _when printing_. MMU 3.0.0 fw. Here is a video: https://youtu.be/z9jfaW7bJyQ

Yip, that is by design as well.

I gave up, and rolled my firmware back today. The MMU had become completely unreliable in loading filament. Rather disappointed.

**Comment by Prusa-Support** [comment]
Basically, the lights now have quite specific meanings during the bootup (for analytical purposes) and only match the selector position when loaded with filament to print.

The selector's position is generally not relevant as long as there is no filament loaded so, as of now, the light won't match the position of an empty selector.
I totally understand that some users are already used to the old fashion position lights however the firmware was totally rewritten and improved on all aspects, and this is not a bug but intentional.

Michele Moramarco
Prusa Research
