### ISSUE TITLE
[BUG]<REVO 6 thermal anomaly>

### ISSUE THREAD

**Issue by jcharouz** [prusa3d/Prusa-Firmware#4296]
**Printer type** - MK3S, with IKEA LAK enclosure
**Printer firmware version** - E3D REVO FW MK3S+ 3.1.3

**MMU upgrade** - no
**MMU upgrade firmware version** - no

Octoprint

**Describe the bug**
Initial calibration and heat up went ok. After i started the print, i kept getting thermal anomaly error. The printer did not stop and the print was fine, but the error kept coming back.
  
**To Reproduce**
Only thing i can think of is that the calibration process was done with a standard brass 0.4 nozzle and before the print, i switched it to the obsidian X 0.6 nozzle
  
**Expected behavior**
no thermal anomaly
  
**G-code**
  Please attach a G-code. This will make it easier for us to replicate the error.

**Video**
  Please attach a video. It usually helps to solve the problem.

**Comment by 3d-gussner** [comment]
@jcharouz Thanks for the bug report. As your Thermal model calibration has been done with the 0.4 brass nozzle and the errors were reported after switching to 0.6 obsidian X I would guess that the TM values are bit off due to different thermal behavior.

ANY THERMAL CHANGE may/will cause issues and TM warnings/errors as the firmware is tuned for one specific setup and "simulates" the thermal behavior while comparing it to measured. If these are too far off the TM warnings and TM errors are triggered.
- Nozzle change (with different thermal properties)
- Heat block
- Fan/Fanduct
- Enclosure vs open/no enclosure
- etc. 

Also the PID values are "tuned" for 215°C so if you print very high temps it might be useful to have different PID settings in the Slicer profiles.

If you are using OctoPrint please check your terminal output and check how the temp curves looks like with different nozzles and temperatures.
- Temperature waves are indicate "bad" PID values -> need PID calibration for the nozzle and material combo, especially very high temps can cause issues as your printer may overshoot and MAXTEMP ERROR out. 
- In terminal you can look for TM error values and see how often these happen.

Possible solution:

1. Copy from `M503` all `M310` (TM) and `M301` (PID) gcode commands and values and save them somewhere as a reference.
2. Run the LCD Calibration -> Thermal Model cal.  for the most used nozzle. It will store YOUR TM values in eeprom.
3. Run LCD Calibration -> PID calibration for the most used nozzle and material. It will store YOUR custom PID values to eeprom.
4. Make another copy of `M503` after the calibrations tuned for **your** printer setup.
5. Change to nozzle that causes TM warnings and errors.
6. Run PID tuning `M303 E0 S<temp> C5` where `temp` depends on material you are printing with. 
   a. Copy and save the `P`, `I` and `D`  values (not permanent to eeprom)
7. Run for this nozzle `M310 A F0` (without checking existing TM values)
   a. Copy and save the TM values  (not permanent to eeprom)
8. Create custom Slicer Profiles
   i. Printer profile with obsidian X nozzle with 
      a. Obsidian X TM `M310` gcode in start gcode from step 7.a
      b. Normal TM `M310` gcode in the end gcode from step 2 to step 4
   ii. Filament profiles with PID `301` gcode from step 6a
