### ISSUE TITLE
[BUG] Big problems after firmware update, danger to destroy hot bed

### ISSUE THREAD

**Issue by Escrich** [prusa3d/Prusa-Firmware#4354]
**Printer: Original Prusa factory assembled Prusa I3MK3S**

**Printer firmware version: prusa3d_fw_MK3S_MK3S+_3_13_0_6873**

No MMU

**SD card or USB/Octoprint**
Doesn't matter, doesn't apply

**Describe the bug**
What you are playing at?

I was flashed the new firmware from Prusa Slicer, after the machine reboots, the screen shows a message showing that it will take 24 MINUTES!, yes 24 minutes, to setup the machine, then starts saying about to REMOVE the metal sheet, in order to calibrate z axis and place a sheet of paper instead of it, I'm in doubt, but are your instructions, then starts to move, goes to the upper position, and after a couple of seconds starts to go down, then even having paper, starts to SCRATCH and DESTROY the hot bed, I just make a reset, and then machine is showing the message about to make first layer calibration, if I will have again a kind of issue like that, I will claim you for a new hot bed, in the previous firmware update was the same, I'm starting to become in panic every time you make a new firmware update!, actually, after latest three of four updates, I'm working with thermal imaging disabled, and crash detection disabled, what will I need to disable after today's update?

**Comment by sarusani** [comment]
Please read the [user manual](https://help.prusa3d.com/article/xyz-calibration-mk3-mk3s-mk3s_112351) :

(This is just  one paragraph from it, check the full page that's linked above!)

Place a sheet of paper (e.g. the included cheat sheet) between the nozzle and the heatbed. If the nozzle catches the paper, immediately press the Reset button. Your P.I.N.D.A. sensor is probably set too high. Lower it down by 2 - 3 threads and run the XYZ calibration again.

**Do not leave the printer unattended during this calibration, otherwise, you may end up with a scratched heatbed. The paper is just an indicator, not protection!!!**

**Comment by Escrich** [comment]
The pinda don't detect the bed without the metal sheet, the printer was absolutely well adjusted before

**Comment by Escrich** [comment]
After some years, believe me, I don't need the manual to make calibration on my MK3s

**Comment by gudnimg** [comment]
> The pinda don't detect the bed without the metal sheet

The steel sheet should be removed… if the nozzle catches the paper then your PINDA is too high according to the manual. 

I don’t see how this is a firmware issue as it sounds like you arent following the calibration steps.

**Comment by Escrich** [comment]
My z offset, after calibration is -0.283, do you really think that it's too high?, I'm adjusting, and working, and taking high care of my Prusa, during the last four years, I know my machine, sorry, I'm still thinking this way of calibrate it is a mistake

**Comment by Escrich** [comment]
After my manual setup, the printer has ended working without a problem, and has made good big part, without any problem

**Comment by Escrich** [comment]
Sorry was a mistake when I was angry
