### ISSUE TITLE
[BUG]<Autoload stopped working after update to FW3.13.1>

### ISSUE THREAD

**Issue by PGlyre** [prusa3d/Prusa-Firmware#4373]
**Printer type** - MK3S+
**Printer firmware version** -  3.13.1

**Describe the bug**
  I am experiencing some problem, put FW 3.13.1 on one of my MK3s+ and after this installation Autoload has stopped workings.
  
**To Reproduce**
  Just update FW to 3.13.1.

**Comment by gudnimg** [comment]
Are you upgrading from 3.13.0? 

3.13.1 only touched one Z move in XYZ Calibration so couldn’t have broken Autoloading (it’s at least extremely unlikely)

**Comment by PGlyre** [comment]
No. sorry for my bad background information. I upgraded from 3.12.2

**Comment by nastevens** [comment]
I also upgraded from 3.12.2 to 3.13.1 firmware and I'm experiencing the same problem - autoload doesn't work at all on my MK3S+.

It seems like this isn't affecting every MK3S+ so let me know if there's any debug information I can collect to help figure out the underlying issue.

**Comment by octopuss** [comment]
I've upgraded my MK3S+ to 3.13.1 yesterday and have same problem. Filament unload works but autoload after change, or separately after restart not. I have to manually move extruder "axis" to use new filament.

**Comment by octopuss** [comment]
Today I've tried self test, because Support->Sensors->filament sensor was showing 0, and previously working filament sensor was marked as "wrongly wired". So i checked the wires (working ok for 1,5 year) and found nothing suspicious. After that I've upgraded to 3.13.2-RC1 and problem is solved, filament sensor is working again.

**Comment by Coffeeroast** [comment]
I also upgraded from 3.12.2 to 3.13.1 firmware and I'm experiencing the same problem - autoload doesn't work at all on my MK3S+.
After that I've upgraded to 3.13.2-RC1 and problem is the same. 
If I begin the test under Support/Sensor info, the Sensor functions perfectly.
However, under settings / Filamentsensor the sensor is switched on, Autoload and outlet = N/V.
If I downgrade, functioned of the Autoload also again perfectly.

**Comment by nastevens** [comment]
:man_facepalming: So I'm an idiot... today I restarted my printer and was greeted by a message that "MK3 firmware is running on MK3S". I had seen that message after the firmware update before but it didn't actually register what it was saying (I thought it was a standard bootup message). After installing the [correct firmware for the MK3S+](https://help.prusa3d.com/downloads/mk3s/firmware) autoload is working again.

This is absolutely my error, but I'm wondering if stronger wording on the message might have woken me up. Maybe start with a big "WARNING" or something similar? I'm curious if this is the same issue for you @Coffeeroast @PGlyre @octopuss?

**Comment by Mezza-UK** [comment]
I have a MK3S+ and MMU3 - 3.13.2 Revo and MMU3 3.3.1 and I am experiencing a similar issue. The extruder motor stutters and autoload is not activated when the sensor is triggered. Took apart extruder, heated to PLA temps and I am also unable to move the extruder via move axis option - it just stutters.

**Comment by TH1813254617** [comment]
I have the same problem. The autoload seems to stop working after a cold pull. It works sometimes if I unload filament normally. One thing that may be worth testing is to simulate a normal unload and see if that fixes the autoload.

My sensor is working reliably, I tested under Sensor Info. I am running the correct firmware on my MK3S+.

I'll try out 1.13.2.

**Comment by TH1813254617** [comment]
Update, after updating to 1.13.2 the autoload still did not work. Testing it under Support Sensor info shows the sensor to work properly.

I tried verifying the filament sensor under HW setup and now autoload works again!

**Comment by 3d-gussner** [comment]
@TH1813254617 Thanks for the update. Which FSensor version do you have `0.4 or newer` ?
Now the autoload works again after LCD Settings -> HW Setup -> FSensor Detection?

Can you please check the voltages are shown in LCD Support -> Voltages of the IR sensor when triggered / not triggered and report these back?
Wonder why a FSensor Detection has fixed the issue for you.

**Comment by TH1813254617** [comment]
Hi, sorry for the late reply. I was not following this thread.

My sensor version is 0.3 or older (extremely early adopter of the MK3S+ upgrade kit). Voltage is 5.0V without filament and 0.1V with filament.

My printer was shipped 2018-11-12 as a MK3. The autoload always worked after the MK3S+ upgrade up until that firmware update.

It is important to note that filament detection always worked for me, even when autoload didn't. I could see the sensor info change when inserting and removing filament. The printer just didn't load filament or give the prompt to preheat. I do not know why verify sensor fixed my problem. I did not try toggling autoload because I couldn't find the setting at that time (the autoload filament section says it's active).

Autoload has been working reliably since my last update.

**Comment by HolgerHU** [comment]
Hello,
I still use an older (08.2018) MK3 with the laser sensor. It still works without any problems. Since the update to FW3.13.2, autoload no longer works. I therefore only load the filament manually with the autoload function switched off. However, filament runout is reliably detected. Autoload still worked with FW 3.11.x.

**Comment by PGlyre** [comment]
> **Printer type** - MK3S+ **Printer firmware version** - 3.13.1
> 
> **Describe the bug** I am experiencing some problem, put FW 3.13.1 on one of my MK3s+ and after this installation Autoload has stopped workings.
> 
> **To Reproduce** Just update FW to 3.13.1.

**Comment by PGlyre** [comment]
After i have reinstaller 3.13.2-7080 it's seems that  autoload is working perfect
