### ISSUE TITLE
  [ENHANCEMENT]<User defined preheat presets>

### ISSUE THREAD

**Issue by RetireeJay46** [prusa3d/Prusa-Firmware#4416]
It would be useful for there to be user-defined preset temperatures for the preheating function.  My suggestion would be to create one or more small files stored on the SD card for this purpose.  Perhaps one file per preset.  
An alternative would be to store them in EEPROM (M500), but this is not as easily accessed by the typical user and runs into possible problems with version compatibility.

**Comment by 3d-gussner** [comment]
@RetireeJay46 Thanks for the idea. As we have limited resources on the printer we had already to decline similar requests as these are way too "costly".
 
You can create the SD card preheat gcode files quite easy. Please use a good editor like `notepad++` instead of notepad on Windows. 

```
M104 S[first_layer_temperature] ; set extruder temp
M140 S[first_layer_bed_temperature] ; set bed temp
M84 ; disable motors
```
The `M84` at the end is to prevent a warning that the gcode file isn't incomplete.

We introduced also a quick jump to 200°C and 50°C in FW 3.13.2 see https://github.com/prusa3d/Prusa-Firmware/releases that should also make it easier to set your custom temperatures.

Hope that helps.

Please consider to close this ticket.

**Comment by RetireeJay46** [comment]
Thank you, @3d-gussner
