### ISSUE TITLE
[ENHANCEMENT] MMU2S retry could be better in some cases

### ISSUE THREAD

**Issue by PxT** [prusa3d/Prusa-Firmware#4598]
**Printer type** - MK3S
**MMU Upgrade** - MMU2S

I just completed a 4 day MMU print (https://imgur.com/a/v0FHA4u) which turned out flawlessly. I had 4 interventions in that time, only one of which was legit - due to a filament issue. For the other three I checked the printer and found it had been sitting for some unknown amount of time with a "FINDA didn't trigger" message but ALL THREE TIMES I simply hit retry and it resumed flawlessly from there without any other maintenance or action on my part. I think the latest firmware has some auto-retries built in but maybe this can be enhanced? I lost hours of time with the printer sitting idle waiting for nothing more than someone to click the selector. I don't know what the solution is, besides maybe just increasing the number of retries, but I'm opening this issue for any discussion.

**Comment by DRracer** [comment]
Increasing number of retries is possible (it's the printer's responsibility to issue a "retry" into the printer). 

However, during our internal tests, we have seen scenarios when a simple retry might have helped, but it always turned out to be a problem with some sensors (FINDA or Filament sensor usually need some adjustment).

Moreover, simply increasing the number of retries might cause more damage in some other scenarios - e.g. unnecessarily stressing or even grinding the filament.

So for now we are not planning to increase the default number of 3 retries. If you think it would help in your case, please feel free to patch your printer's firmware, it's open source :wink: .
