### ISSUE TITLE
Increase max size of SDCARD for 3D printer

### ISSUE THREAD

**Issue by ror1948** [prusa3d/Prusa-Firmware#4632]
3D printer MK3S does not read a 32g SDCARD.

**Comment by u89djt** [comment]
It does if you format it to FAT32.
Notes on the prusa site: https://help.prusa3d.com/article/sd-cards-and-usb-drives_112291
I could add this description of using a built in windows command, being clear that I don't recommend any specific set of actions because you have to make sure for yourself that you don't format a wrong drive: https://www.diskpart.com/diskpart/format-sd-card-using-diskpart-0310.html
Best wishes from a fellow user.

**Comment by ror1948** [comment]
it is fat32
![sdcardfat32](https://github.com/prusa3d/PrusaSlicer/assets/98917767/4ff74714-d18c-40da-abc4-72513d37946b)
formatted with special sdcard formatter

**Comment by neophyl** [comment]
I've got a 32gb card in my Mk3 too and been using it for years.

**Comment by ror1948** [comment]
Ok reformatted on win10 and card is working.
Thanks

**Comment by ror1948** [comment]
Thanks

**Comment by 3d-gussner** [comment]
Nice to see you all interacting and help each other, very appreciated. :hugs:
