### ISSUE TITLE
[FEATURE REQUEST]<Auto-Unload Filament Toggle for Prusa XL

### ISSUE THREAD

**Issue by bmirwin89** [prusa3d/Prusa-Firmware#4671]
I have a 5 tool XL and I waste a lot of time after a print has finished waiting for the printer to heat back up, process tool changes, and unload all five tools.  It would be nice to have an option I can toggle on if I know I won't be reprinting with the same spools to have the printer unload all tools at the end of the print while it's still hot.  That way when I come back to the printer I can just remove the spools immediately and put them back into dry-boxes.

**Comment by JonMrowczynski** [comment]
Hello bmirwin89, I hope that you have been doing well!

It appears that your issue is for the XL. The repository for this can be found [here](https://github.com/prusa3d/Prusa-Firmware-Buddy). As stated in the README for [this repository](https://github.com/prusa3d/Prusa-Firmware?tab=readme-ov-file#prusa-firmware-mk3) "This repository contains the source code and the development versions of the firmware running on the [Original Prusa i3](https://prusa3d.com/) MK3S/MK3/MK2.5S/MK2.5 line of printers."

From my understanding of what is usually done in this case, it would be most helpful for you to close this issue here and repost it on the [XL firmware repository's issue tracker](https://github.com/prusa3d/Prusa-Firmware-Buddy/issues) so that it gets seen by the right people.

**Comment by bmirwin89** [comment]
Hi Jon, 

My mistake.  This is the link I was given my Prusa support to request this feature.  I see it's already been requested here, so I just added an additional comment.  

https://github.com/prusa3d/Prusa-Firmware-Buddy/issues/3444

Closing this one here. Thanks!
