### ISSUE TITLE
[FEATURE REQUEST] Resume at Z-height for failed prints

### ISSUE THREAD

**Issue by Avamander** [prusa3d/Prusa-Firmware#4686]
If it makes sense, enter what type of printer or upgrade the feature request applies to.
**Printer type** - MK4

**Is your feature request related to a problem? Please describe.**

Some print failures are quite recoverable, such as nozzle clogs. I have currently manually measured and searched for the correct layer at which to resume the print. This is really finicky and mistakes can even damage the printer (one might forget to remove bed leveling G-code for example).
  
**Describe the solution you'd like**

I'd like to pause the print, restart at a specific layer or Z-height (maybe even bring the extruder to that height to be extra certain). This wouldn't require rewinding, it would be re-starting at a specific height. I'd even be happy if I could restart from some line `n` I could look up in G-code viewer. Anything over manually editing gcode would be better.

**Comment by 3d-gussner** [comment]
@Avamander This is the MK2.5/s and MK3/S/+ 8-bit firmware repository. Please close this issue here and open it in the MINI, MK3.5, MK3.9, MK4 and XL 32-bit repository https://github.com/prusa3d/Prusa-Firmware-Buddy/issues.

>I'd like to pause the print, restart at a specific layer or Z-height (maybe even bring the extruder to that height to be extra certain). This wouldn't require rewinding, it would be re-starting at a specific height. I'd even be happy if I could restart from some line n I could look up in G-code viewer. Anything over manually editing gcode would be better.

I doubt that this feature will be possible to code in the firmware due to needed resources. PrusaLink on MK4 also runs on the controller board that will also not fit.

**Comment by 3d-gussner** [comment]
Closing as wrong repository
