### ISSUE TITLE
[Feature request] extruder motor filament stuck detection. 

### ISSUE THREAD

**Issue by AlexGuld** [prusa3d/Prusa-Firmware#476]
I would be nice if there was detection on the extruder motor, so if the filament got stuck outside the printer,                  eg. on the spool holder, it would sens it and pause the print and ask for help. 

I have had an episode that ended with the printer "pulling" the z axis crooked.

**Comment by AnHardt** [comment]
Marlins focus is on software.
If there is a reliable, available, affordable filament motion device we will support it sooner or later.
But we will not develop such a device.

We can discuss pros and cons of concepts, chips, ... here. Maybe you can win the heart of a single developer to make the hardware for a project here.

I know. It's a hen - egg problem.

[Ooops! Wrong project]

**Comment by AnHardt** [comment]
Just some random thoughts.

Would filament motion detection have helped with your accident?
No! The filament moved until it was too late. 

Are you looking for a filament spool motion detection system?
That motion is usually very uneven. Sometimes moving fast - than not moving for minutes. When not bowden, only very loosely coupled to the extruder, more to head movement.

Would a filament tension sensor have helped?

**Comment by cnlson** [comment]
this should be part of the skipped step detection if the e motor is clicking when trying to feed from the spool

**Comment by Prusa-Support** [comment]
Thank you for sharing your ideas.

The developers worked on the MK3 Laser Filament Sensor to be capable of detecting non-moving filament but this was not possible to be reliably implemented, probably because the Laser Filament Sensor was too sensitive and also detecting shaking as running filament.
Since the MK3S, the idea was abandoned, in fact, the filament sensor was changed for the IR Filament Sensor (a semi-mechanical one) . The latter can only detect the presence of a filament and not the movement, proving itself to be more reliable in this.

As for the crash/stall detection by TMC drivers, it works reliably enough for the X and Y axes, but not for the Extruder, as briefly explained in issues #505 and #2827.
The reason is probably that the extruder motor works in a too large range of speeds; also because the load on it largely varies between motors, print parameters, hardware conditions (degradation/maintenance), ambient factors...

This issue will be closed. Please comment below or open a new issue if you think the issue deserves further study.

Michele Moramarco
Prusa Research
