### ISSUE TITLE
Optimize bed leveling procedure

### ISSUE THREAD

**Issue by RacingHell** [prusa3d/Prusa-Firmware#560]
Last measured point is the most far away one from home-position. Measuring spiral-wise would reduce necessary movements.

**Comment by fiveangle** [comment]
What would be more interesting I think is to start the calibration so final probe point is the home position like you suggest, but also make that the start probe point, then compare and if different than the initial, assume PINDA calibration issue and restart probing again, then throw error if fails a second time.

**Comment by fiveangle** [comment]
Also, the transverse move from the current last probe position to the purge line start location really should be faster, as it is excruciating to watch :)

**Comment by Crunch69** [comment]
pinda should run the 9 points twice and then take and average to provide a more accurate result

**Comment by fiveangle** [comment]
@Crunch69 - that would be an extremely wasteful use of our collective time and would serve only serve to cause further downstream issues as it could only mask a drifting PINDA probe, resulting in final measurement that is guarenteed to be off (since you are potentially averaging measurements taken before and after a probe drift).

The current FW already samples each spot 3 times in succession.  The PINDA probe doesn't typically show any sign of high deviance from measurement to immediately-successive measurement.  One double-measured probe point at the start and finish should be sufficient to determine if calibration has drifted appreciably during the probing process, and if so, trigger recalibration, then restart the entire probing process after recalibration was complete.  If it then failed again, throw a user error because either the PINDA is faulty, or the printer is on fire and should really be investigated ;)

-=dave
