### ISSUE TITLE
Add beep-beep-beep when pre-heat temperature reached

### ISSUE THREAD

**Issue by jcwren** [prusa3d/Prusa-Firmware#697]
It would be nice to have the printer beep several times when the pre-heat option is selected from the menu and pre-heat temperature targets are reached.

**Comment by MarekC3D** [comment]
We plan to make more use of beep-alerts... also the possibility to switch-off beep completely :-). I will add you feature request to our Jira.

**Comment by jwest75674** [comment]
jcwren, you can also add these to the starting Gcode to most slicers with something like:

;beep
M300 S2349 P53 ; Play beep sound
G4 S1 ; Wait 1 second
;beep
M300 S2349 P53 ; Play beep sound
G4 S1 ; Wait 1 second
;beep
M300 S2349 P53 ; Play beep sound
G4 S1 ; Wait 1 second
(This is copied from my Slic3r settings just after the set and wait for bed temp Gcode, M109)
As always, don't edit Gcode if you're not familiar with it though!

**Comment by jcwren** [comment]
That's a good idea for a print, but it won't work when using the pre-heat option from the menu. And since you have to pre-heat to unload filament...

**Comment by cnlson** [comment]
I second this, I would love a beep alert on preheating the bed

**Comment by Pyronious** [comment]
Adding my vote for audible beeps when pre-heat (from front panel menu) is completed.

**Comment by kevinp2** [comment]
I add my vote to this.  I have my printer in another room and waste a lot of time because it doesn't report when it is done.

I would like to request this as a simple configuration item.  A good place might be:

Printer Settings > Advanced > General > Beep After Pre Heat Completed. 

Also see [Issue 458](https://github.com/prusa3d/Prusa-Firmware/issues/458) which is similar.

**Comment by gudnimg** [comment]
Closing in favor of more recent duplicate https://github.com/prusa3d/Prusa-Firmware/issues/3815
