### ISSUE TITLE
Printer reset, "crash detected," then drove the nozzle into the bed

### ISSUE THREAD

**Issue by zehkaiser** [prusa3d/Prusa-Firmware#718]
MK3, 3.2.0-RC2

I was about 4 hours into a print when I turned on stealth mode. Before it kicked in, I started lowering the print speed. The warning for stealth mode popped up and I clicked to dismiss the message. The LCD became a garbled mess, but moving the wheel changed the mess to other random characters. I thought the speed adjustment was being made, but I couldn't see it. I clicked to confirm and the printer reset. Then I received a message that a collision was detected. The printer homed X/Y, then lowered the Z into the print bed for about 2 seconds until I mashed the reset button.

**Comment by Prusa-Support** [comment]
Sadly, this issue has been silent so far. Therefore, it could be closed as stale.

Before closing it, I wonder if the problem persists or happened recently again.
Are you are able to reproduce the issue and make a video of it?

I can't be sure what went wrong but it may seem the case of a glitch.
Glitches are difficult to track down, reproduce and explain. The causes of a glitch could be many and vary a lot.
It could be due to an overloaded motherboard due to a very specific combination of commands and processes.
It could be due to electrostatic interference: ensure the PSU is correctly connected to the ground, and touch the PSU to discharge yourself before interacting with the printer if you happen to feel shocks on the objects around you.
Overlapping commands, motherboard overload, and electrostatic interference could also be caused by 3rd party devices: try disconnecting any external board, UPS battery, LED stripes, etc...
It could be a matter of wiring and interference due to damages on a wire or on the motherboard.
A glitch may also be related to a corrupted SD/USB flash drive, corrupted files, files with too long naming, or files including unsupported characters (in the naming or in the code).

Please provide further information or please close the issue if the problem no longer persists.

Michele Moramarco
Prusa Research
