### ISSUE TITLE
3.2.0 Layer Shifting

### ISSUE THREAD

**Issue by mattracing** [prusa3d/Prusa-Firmware#759]
Hi People, last thursday I received my MK3 kit and assembled it without any problems. I updated the firmware to 3.2.0 and made all the calibrations. I have printed many small parts without problems.
Yesterday I put printing one of the fuselages of the P38 from 3DLabprints (GCODE from them for the MK3) and I've got a layer shift (at about 12 cm). The MK3 is set up to normal mode.
 I also have an MK2 clone with RAMPS-TMC2130 drivers and Marlin. I had that issue and was because of low current parameters and high speed. But that was in Stealth Chop Mode. I understand "Normal" Mode in MK3 is Spreadcycle and it shouldn't have these problems of losing steps. 
Can please someone guide me with this? Is this already corrected in 3.2.1? I don't want to try,  I want to know first. Thanks

**Comment by mattracing** [comment]
I'm still having layer shifts. Speed is equal or lower than my MK2 clone and still shifting layers. The fail stats says (and I can check that) that the steps were lost in the Y axis. I verify everything else, belt tension, etc.,  etc. etc. For me it is clear that the Y driver current is too low. As the MK3 is a packed firmware, can someone please tell me how can I correct this for my printer? Prusa Support sent me here, so...

**Comment by TechnoidAlpha** [comment]
I've been having similar issues, Y-axis layer shifting. for me, the shifts happen when it rehomes and does its automatic layer correction. I disabled crash detection and everything seems to be working for me. I'll probably keep crash detection off until something fixes as I think it is triggering wrongly and then homing badly or something.

**Comment by mattracing** [comment]
Yes, yesterday I found in the Prusa Forums many people with this issue and have tested that. I disabled the crash detection and for now it is working. I guess the crash detection is too much sensitive and it is the cause of the layer shifting (in my case). As you said, when it comes back it fails to continue in the same place and that produces the shifting.
 I won't close the issue as disabling the crash detection doesn't seem to me a solution.

**Comment by gdombiak** [comment]
Same boat here. Y belt tension at 240 and still running into crash detection (even though nozzle did not hit anything). Printer homes itself and then resumes printing but there is a nice line in the print now. Ended up disabling crash detection (besides disabling filament sensor) and things run good. Would be nice to be able to enable these features back.

**Comment by mattracing** [comment]
I also didn't say before, but now I'm working with firmware 3.2.1 and the issue is still there.

**Comment by jgm1986** [comment]
I have the same problem. I have printed 3 dice towels with the same gcode. The first print worked as expected without issues. The last two dice towels has the same layer shift at the same place. I'm using the last stable version of Slic3r Prusa edition and MK3 firmware v3.2.1.

The layer shifts happens after a crash detection.

**Comment by HFMan** [comment]
I believe the layer shifts occur due to the z axis potentially not being perfectly perpendicular to the x-y axis.  When you have a 'crash', it rehomes, but at a higher z than the original home (which was at less than 1mm off the bed.)  Once you go higher and higher, the home (in particular the x-home) may not be identical due to perpendicularity, or perhaps what the x-axis bumps into.  Y axis should home pretty much the same location no matter what the z-height.

**Comment by TheZeroBeast** [comment]
Referencing to PRUSA Printed Parts MK3 PullRequest I've just created addressing one cause of inaccurate Y-Axis homing which results in layer shift when a crash is detected.
https://github.com/prusa3d/Original-Prusa-i3/issues/76

To try you would install part, run Selftest in Firmware to set belt tension with new part.

**Comment by TheZeroBeast** [comment]
Hi All,

I may have a solution to our small layer shifts when recovering from crashing.

Here is my thought process that will be followed with a pullrequest for the code changes although PRUSA should be able to improve on my approach.

- I have been running the Y-Axis-Motor-Mount part in the above post with about 80% successful recovers after crash. (to clarify, successful rehome IMHO is when that axis doesn't appear to layershift)
  - On investigation of terminal readouts there is a chance that the single endstop probe will return false value off by over 10 whole steps.
  - My thinking is to do a number of endstop probes and filter out false values, hopefully close to 100% if not 100% of the time.
- I modified the firmware with a new 2130 home method that is based on the 'G28 C' calibration method for when X or Y axis is homed.
  - I noticed that once printing the first crash that was introduced resulted in a visible X-Axis step but subsequent crashes all aligned to the correct coordinates. This got me thinking, I know G80 does home all then mesh-bed before the print, does something go wrong at this point with X-Axis home. To test if this is the case I added ‘G28 X Y’ right after ‘G80’ in my start-gcode and ran a test. Each crash recover from the first to the last were all correct.

![crashstep](https://user-images.githubusercontent.com/20939095/42406586-320755fc-819a-11e8-8c12-f7100595883b.jpg)
_Here is a test cube with a step at first introduced crash, ignore inconsistant extrution, printed at 300% speed to save time_

![crashfixed](https://user-images.githubusercontent.com/20939095/42406582-1b3b4bda-819a-11e8-8473-9177d3a10240.jpg)
_Here is the same test cube printed with G28 X Y again after G80 :-D_

 - I have done a few prints since and a tall test print with 30 crashes periodical introduced throughout on both X and Y without any steps, photo to come soon.

Let me know if anyone is willing to test my firmware changes and verify my findings

**Comment by 3d-gussner** [comment]
@TheZeroBeast Is it possible that https://github.com/prusa3d/Prusa-Firmware/pull/927 fixed it?

**Comment by TheZeroBeast** [comment]
Hey @3d-gussner, I will have to re-compile with my changes and test when I have time, it is possible #927 might fix G28/G80 having to be homed post meshbed leveling. It doesn't appear PRUSA has made changes resulting in more accurate homing from crash to crash though.

**Comment by TheZeroBeast** [comment]
Hi guys, even with latest build I got layer shifting on a detected crash. I then tried with my calibration home routine then got burnt again on a 40h print that detected an X crash, attempting to rehome and resulted in a shift. I'm resulting to disabling like majority of people until we can have an official word from PRUSA Research.

**Comment by Prusa-Support** [comment]
Thank you for the report and for sharing your ideas.

In the firmware _v.3.2.0_ there was a little re-work on the Calibration processes. Minor XY homing issues arose during the testing as highlighted by pre-release firmware versions, but those have apparently been addressed.
This said, there were modifications that may concern this discussion, but there were no confirmed issues, not even in the following few releases.
On the order hand, this issue is stale now, and the firmware has constantly been improved since. 

The modification mentioned by @TheZeroBeast could reduce the bounce across the right side of the Y-carriage, but such bounce may be negligible or not concerning. So far the "bounce" is not a confirmed issue.

This issue will be closed for now because stale. Please comment below or open a new issue if you think the issue deserves further study.

Please review the most common causes of layer-shifts and consider contacting the Technical Support before posting about new similar problems.
https://help.prusa3d.com/article/layer-shifting_2020
https://help.prusa3d.com/article/customer-support_2287

Michele Moramarco
Prusa Research
