### ISSUE TITLE
3.2.0-555 Hot extruder motor disforming PLA

### ISSUE THREAD

**Issue by JoePrints** [prusa3d/Prusa-Firmware#780]
60% into a print, the printer restarted itself (false power failure detection). Upon resuming, the extruder started clicking and continued to restart (false power failure) 2 more times, clicking the whole time.
Upon further investigation, the filament (PLA) was so disformed for the hot extruder motor that it could not make it's way into the heatbreak…. and had to be pulled free of the extruder by hand.

I have attached the Gcode it was printing.

[ECO_subzero_mask_v2 code.txt](https://github.com/prusa3d/Prusa-Firmware/files/2050268/ECO_subzero_mask_v2.code.txt)

**Comment by jgm1986** [comment]
I've the same issue. Prusa has send me a new extruder motor for remplace it. I've pending change it...

**Comment by chhu** [comment]
Same issue here! I have this issue since 3.2 with my MK3, after a while into the print extruding stops, at first I thought it was a filament jam but the filament is loose. The extruder motor was always really hot and I think the extreme heat from the extruder motor finds its way along the shaft to the gear and makes the filament slippery. I think this is related to #769 . The question is if it can be fixed with firmware (less amps) or if it is a problem of the motor... I cannot print at all anymore!

**Comment by JoePrints** [comment]
PLA is the only thing I have troubles with, and only after about 6hrs of printing. If it's less it does fine....anything longer and my MK3 turns into a clicking fool

**Comment by chhu** [comment]
Hmm could be the hot weather here is adding to the issue. My extruder gear is pretty slimed with PLA already... Can you touch your extruder motor after an hour of print without getting burnt?

**Comment by JoePrints** [comment]
Again tonight, it detected a false power failure. I was sitting next to it on my desk, and there was no power failure. Then upon resuming the print, it layer shifted along the x axis.
Is there an issue with the PSU perhaps?

**Comment by Crunch69** [comment]
Extruder motor runs cool with FW 3.2.1 have ran many 11 plus hour prints and the motor is not even warm
