### ISSUE TITLE
FW 3.2.1-576 MK2.5 Activating filament sensor during the print froze the machine

### ISSUE THREAD

**Issue by giudiceanto** [prusa3d/Prusa-Firmware#799]
Hi, during a print I went in the tune menu, >>accidentally<< clicked on the filament sensor wich was [off] and turned it [on]

the print stopped and the whole machine froze, the menu was frozen too.
had to press reset and abandon my print

**Comment by Prusa-Support** [comment]
Hello! Sorry to see this has been left unanswered for so long. I believe this should have been fixed in the meantime with newer firmware releases, has it occurred with newer releases? In case of similar issues do not hesitate to let me know info@prusa3d.com mentioning me ("attn: Alessandro"), we'll look into it. Closing the issue for now. 

Alessandro Pantaleo
Prusa Research
