### ISSUE TITLE
Add "// action:pause" and "// action:resume" for filament runout sensor

### ISSUE THREAD

**Issue by kortschak** [prusa3d/Prusa-Firmware#805]
Currently "// action:pause" is used for fan speed error to communicate with OctoPrint, but not for filament sensor error, making filament sensing useless when printing through OctoPrint.

Originally reported as a request to OctoPrint foosel/OctoPrint#2673.

**Comment by PavelSindler** [comment]
We are currently working on improvents of crash detection and filament detection when printing using Octoprint.

**Comment by kortschak** [comment]
Thanks. It was a disappointing discovery today that it didn't exist - fortunately only on the third layer.

**Comment by FotoFieber** [comment]
Just made a print with two filament changes (filament run out) and got no notification in octoprint. Would be nice, if this issue could be solved... :)

**Comment by marfink** [comment]
Any news on this feature request?

**Comment by randominternetuser** [comment]
This would be nice to see working!!

**Comment by kortschak** [comment]
@DRracer (handle chosen by recentness of commits to this repo) Is there any intention to progress this?

**Comment by mikulik86** [comment]
It is nice that since adding basic Action Commands in 3.10.0 the Octoprint is indeed reacting to pause/resume/cancel print from the printer controls. 

**But why still no filament runout!!**

Please, add this functionality so that Octoprint users can be remotely alerted that the printer is actually not printing.

This is what I suggest in the event of filament runout:
```
//action:paused
//action:notification Filament runout detected
```

And after loading the filament and resuming the print ofcourse:
`//action:resumed`

This would be extremely appreciated. Thanks.

**Comment by kortschak** [comment]
Still wanted

**Comment by kortschak** [comment]
still wanted

**Comment by 3d-gussner** [comment]
@kortschak Thanks for the reminder. We will look into that. Can't promise when but assigned it to myself.
