### ISSUE TITLE
MK 3 Firmware 3.2.1 Heaters shut down after Filamentchange triggered by filament sensor

### ISSUE THREAD

**Issue by Gountled** [prusa3d/Prusa-Firmware#840]
My filament (PLA) run out during a print and I used the filament sensor (wanted to test it) in order to change the filament.
The sensor triggered and the printer also moved the extruder to the parking position and waited for my action with heaters on.

I changed the filament and the printer started to continue printing, everything fine up to this point.
But I recognized, the heaters (both, extruder and heat bed) shut down. Luckily I was observing this and was able to set the temperature manually up again.

I would consider this as a firmware bug, anyone else observed someting like tis?

Firmware 3.2.1 from PRUSA homepage.
Filament PLA, Extruder 210°C and Bed 60°C

I need to mention: I was expecting the run out, therefore I was sitting beside the printer when it happened and the whole change didn't take more than 3 min.

**Comment by PavelSindler** [comment]
Do you have Octoprint connected to your printer?
Octoprint sends M27 requests periodicaly to get printer status (which byte is currently printed etc.).  There was bug which caused that during crash detection and filament runout detection printer replied with "Not SD printing" and Octoprint reacts to it with turning off heaters. It has been fixed in PR https://github.com/prusa3d/Prusa-Firmware/pull/760. It will be released on github as RC1 version next week.

**Comment by Gountled** [comment]
Yes, Octoprint was connect, but the print was started manually from SD Card. Octroprint was just used for monitoring. I don`t know if that already can disturb the printer?

**Comment by PavelSindler** [comment]
Yes, this is the case I have described. Octoprint sends M27 periodicaly in this case. You can see it in Octoprint terminal.

**Comment by 3d-gussner** [comment]
@Gountled Is this issue still existing with the newest firmware, if not please close issue.
[stale]

**Comment by Gountled** [comment]
The problem is solved by the new firmware.
