### ISSUE TITLE
MK3 Flashing 3.3.0 firmware results in: "External SPI flash W25X20CL not responding" error

### ISSUE THREAD

**Issue by Petclaud** [prusa3d/Prusa-Firmware#896]
Hi, just wanted to report that on my MK3, flashing the firmware to the latest 3.3.0 release results in the error as per the title. I have made several attempts with the same result. Flashing it to the 3.2.1 gives no errors. Trying again the 3.3.0 = error again. 

I use the Firmware Updater V2 program with a USB cable between printer and Windows PC

![20180703_212848](https://user-images.githubusercontent.com/28214663/42290434-7b45e660-7fc5-11e8-8610-45bcce826e13.jpg)

Using Slic3r (1.40.1 RC2) from release 3.2.1 to 3.3.0 gives the same result. Piece of the log file here below:  

![image](https://user-images.githubusercontent.com/28214663/42290727-794d3dca-7fc7-11e8-9b62-cc0362dbb1f3.png)

Once the error occurs, I cannot flash back to the 3.2.1 firmware using Slic3r since the flashing process just wont start. The dedicated Firmware Updater V2 program does the trick however

I see also already an entry on the forum describing the same issue: https://shop.prusa3d.com/forum/general-discussion-announcements-and-releases-f61/firmware-3-3-0-for-original-prusa-i3-mk3-t22743-s20.html

**Comment by adlamy** [comment]
Hi, 
If it can help, the link to my post about this issue on the forum
https://shop.prusa3d.com/forum/general-discussion-announcements-and-releases-f61/firmware-3-3-0-for-original-prusa-i3-mk3-t22743-s40.html#p96587

Regards.

**Comment by Petclaud** [comment]
Update: Also flashing with Slic3r 1.40.1 results in the error (which makes sense since the 1.40.1 RC2 is supposedly to be the same as the final release). 

I just had a chat session with Prusa's Tech Suppport and they promised to look into this.

**Comment by lewnewby** [comment]
This occurs on the 3.3.1 release of the firmware as well.

**Comment by ChrisKrieg** [comment]
Just had this happen to me when uploading 3.3.1 to the Mk3. Cannot perform a factory reset. Will try to upload firmware 3.2.1

**Comment by tomlask** [comment]
I have the same problem. I got 2 MK3 printers. On one upgrade loads without issues, on second got the same error. Boards in both printers looks the same to me. I had to load and stay on 3.2.1 on one machine.

**Comment by tomlask** [comment]
I took closer look on board with firmware upgrade issues.
The problem is... there's no W25X20CL chip on board!
These boards were produced in several versions, 
I got one referenced by assembly manual as version A (without add-on board).
Take closer look at the left side and compare it with that pic: https://ultimachine.com/products/einsy-rambo-1-1
These 3 chips near Z-axis connectors are U12 - U14 on schematic: https://github.com/ultimachine/Einsy-Rambo/blob/1.1a/board/Project%20Outputs/Schematic%20Prints_Einsy%20Rambo_1.1a.PDF
Sheet 5 on bottom of page.
So this is hardware issue - probably first versions were produced without 2Mb SPI flash.
If you have R-packs (resistors) instead of chips and no add-on board the new firmware would not load.

Board with add-on has 3 chips on it, and I'm quite sure these are missing buffers and SPI Flash.
There were no problem since deevlopers started using SPI Flash ;-)

So I need to contact suport for add-on or replacement.

**Comment by Petclaud** [comment]
Hmm if that is true, it explains a lot. Thx for sharing this info 👍 . I guess now Prusa will need to see who has received versions A boards and who another version and furnish replacement boards for the "A-users' or avoid SPI flash.

**Comment by lewnewby** [comment]
I found out what caused the issue for me, I'm an idiot and removed the "Daughter board" from my Einsy quite come time ago to make room in the case and the missing chips are actually on it. This wasn't an issue until FW 3.3.0 but now it is so i have reinstalled the daughter board and all is working well.

**Comment by adlamy** [comment]
This confirm the issue only with A version Einsy board that comes with no daughter board.

**Comment by dikodahan** [comment]
I also have the board version without the daughter card and am experiencing the same issue.

**Comment by bubnikv** [comment]
Please contact the support, they shall be informed about this particular issue.

**Comment by Petclaud** [comment]
Just had a chat with Prusa. They ask for a photo of the board and if proven to be a type A board, than they will ship a 'patch board'. In the electronics assembly manual it is here: https://manual.prusa…ics+assembly/513?lang=en#s8303
