### ISSUE TITLE
MK3 Firmware 3.3.0 - Power Panic triggers when attached to a UPS

### ISSUE THREAD

**Issue by Crunch69** [prusa3d/Prusa-Firmware#898]
MK3 Firmware 3.3.0 - Power Panic triggers when on a UPS.  The power panic is triggering when on a UPS this should not happen.  I have several printers running on UPS and when power to UPS is interrupted all printers attached work perfect except for the MK3 which triggers power panic.  I dont know if this issue is the latest firmware or hardware issue but it is way too sensitive.

**Comment by gdombiak** [comment]
Was this working fine on 3.2.1 or previous versions? This info might help devs narrow things down

**Comment by fiveangle** [comment]
Sounds like your line-interactive UPS is not maintaining adequate sync between signwave input and square wave output, resulting in brown-out detection upon transition.  Not much that can be done there since the less sensitive you make the power panic mechanism to these poorly-designed UPSes, the less power you have available to actually complete the work necessary (write state info to SD card, move extruder away from print).

Regardless, when the power is cut, isn't the correct behavior to trigger power-panic ?

**Comment by Crunch69** [comment]
fiveangle the APC UPS works just fine with Creality CR-10 and a Makerbot they dont skip a beat only the Prusa MK3 FW3.3.0 reacts in this way like the power was cut

**Comment by fiveangle** [comment]
Neither the CR-10 nor the Makerbot have hardware to detect line voltage brown out.

CR-10 brute-forces the matter by constantly streaming writes to the SD card with every command completion and even then the process is not atomic so there is opportunity for missed window to store resume data, while the Makerbot has no power-cut recovery mechanism at all so your comparison illustrates a fundamental misunderstanding of the design.

Hope that helps™ 😉 

-=dave

**Comment by Crunch69** [comment]
dave the issue is not with the cr10 or maker bot they work fine on a ups.  the issue is the mk3 on the same ups stops printing and the cr10 and makerbot keep printing when the ups senses a mainline voltage fluctation.  also note the cr10 is not printing from a sd card it is printing from a raspi running octoprint which is also on the same ups the raspi also does not skip a beat it is just the mk3 that acts like you pulled the power plug

**Comment by Barnabasek** [comment]
Since you have UPS then you don't have much use for the power panic anyway. Simply disconnect the white&black Power Panic cable from the Einsy and problem solved.

**Comment by LarryTru** [comment]
UPS delays power outage, but will not necessarily last long enough.  Reading this thread and another one like it, it seems to me there is evidence that the power outage detection mechanism is more sensitive than necessary.  A re-design should be considered.

**Comment by vedran-dobos** [comment]
Optimal solution:
Add option in a menu somewhere to lower Power Panic sensitivity (or even select exact ms, or a range of ms) for when the printer is connected to an (line interactive) UPS.

Until then, keeping the Power Panic cable disconnected while the Prusa is connected to an UPS is a compromise solution. If you are around and remember to reconnect the PP cable before the battery runs out, you may even save the print if it takes longer than the power outage.

**Comment by someguy4253** [comment]
I AGREE with vedran-dobos, with (ALL) his comment and Option Solution, since I to have this issue with my new MK3S and my UPS has PFC with AVR, (so not a cheap UPS as others have mentioned causing this) but still the power panic triggers every time.
Only reason to use a UPS in my opinion is for brownouts, since no UPS is going to stay up till a print job finishes.  **We just need a way to adjust the sensitivity on the power panic**.
*I noticed there is a new firmware update being released and power panic was listed as being part of it but it did not read as if this issue was addressed. 

**Below is my UPS specs:**
CyberPower CP1000PFCLCD 
PFC Sinewave UPS Series
Capacity: 1000 VA / 600 W
Topology: Line Interactive
Waveform: Sine Wave
Output: 120 VAC ± 5%

**Comment by GunSmoker** [comment]
The problem is not sensitivity of power panic. 

Heaters are turned off - which means something in printer has "detected" power loss (yes, detected incorrectly, but still). The question is - why does printer itself continues to operate normally?? 

This is the issue - inconsistency in power loss detection between two components. Either printer should detect power loss and stop/pause, or it should not detect power loss and continue to operate.

The current behaviour (heaters are off, steppers are on) is a complete mess. Prusa is not a heisenberg's cat.

**Comment by nordurljosahvida** [comment]
stale-revival

**Comment by 3d-gussner** [comment]
@nordurljosahvida As you revived this ticket. Does that still happen? If so please provide more information.
Also important is to know which kind of UPS is used and how it switches and how fast during power outages and back.

**Comment by 3d-gussner** [comment]
Closing ticket again as no response.
