### ISSUE TITLE
MK3 Firmware 3.3.0 -  Filament is not counting while printing

### ISSUE THREAD

**Issue by gdombiak** [prusa3d/Prusa-Firmware#901]
Many people are reporting that the filament counter is not "counting" after the update to 3.3.0. See: https://shop.prusa3d.com/forum/general-discussion-announcements-and-releases-f61/firmware-3-3-0-for-original-prusa-i3-mk3-t22743-s50.html#p96594

**Comment by Olefff** [comment]
Confirm I have this issue too on 3.3.0

**Comment by cnlson** [comment]
I also have the issue
![20180703_004917](https://user-images.githubusercontent.com/1442027/42481835-0a6a510e-83aa-11e8-8a12-c874f9a2eb0f.jpg)

**Comment by PavelSindler** [comment]
Thank you for reporting this issue. We will fix it.

**Comment by PavelSindler** [comment]
It doesn't work during print, but statistics are shown corretly after print is finished.

**Comment by MrArtMonkey** [comment]
Statistics aren't shown at then of my print and the Print time is wrong too.
This was after about 11hrs and 19 minutes printing and 20 minutes from completion.
-6hrs etc. was unrelated to anything as far as I could see.

![zero and backwards since 3 3 0](https://user-images.githubusercontent.com/41086111/42535593-af4a5eac-8487-11e8-8276-dfdb2b221688.jpg)

**Comment by PavelSindler** [comment]
Fixed in PR https://github.com/prusa3d/Prusa-Firmware/pull/919 and released in [3.3.1](https://github.com/prusa3d/Prusa-Firmware/releases/tag/v3.3.1).
