### ISSUE TITLE
3.3.0 Not sending 'Ok' acknowledgement over COM after G28 (and possibly G80) command. Causing disconnects in OctoPrint and possibly other hosts.

### ISSUE THREAD

**Issue by prgmatic** [prusa3d/Prusa-Firmware#924]
Using latest stable octoprint (1.3.8). Every time I run a G28, the printer stops communicating with OctoPrint. More info can be found [here](https://github.com/foosel/OctoPrint/issues/2721) where I opened an issue on the OctoPrint repo.

Edit: Changed title based on what others have figured out.

**Comment by kazoob** [comment]
Does the same still happen when you issue "G28 W" (home without mesh bed levelling) and then "G80" (mesh bed levelling)?

I've noticed the same thing on mine, running OctoPrint 1.3.9-rc2 and MK3 firmware 3.3.0, when printing from the SD card - it will timeout after the homing and mesh bed levelling. Although my gcode file has "G28 W" and "G80" instead of just "G28" and it still times out. However from my limited testing from the OctoPrint terminal, "G28" will timeout, but "G28 W" and "G80" will not.

**Comment by prgmatic** [comment]
@kazibole I'm finding the same behavior as you. 

Edit: I've only been printing exclusively from the Pi however, not the SD card.
Just to clarify, 'G28 W' and 'G80' seem to work fine. 'G28' does not.
I'm still a little cautious about 3.3.0 on octoprint since I had a print just stop for no reason 2.5 hours in.

**Comment by foosel** [comment]
It looks like G28 is lacking the acknowledging ok at its end in 3.3.0 which might be causing this.

**Comment by kazoob** [comment]
FYI I can successfully start and finish an SD card print, with OctoPrint monitoring, with the following gcode:

G28 W
G80
G81

And also adding G80 to OctoPrint's long running commands. I am not sure if splitting the commands as above resolved it or adding G80 to the long running commands list.

**Comment by PavelSindler** [comment]
Thank you for reporting this. Yes, G28 is missing ok. We will fix it and make patch release next week.

**Comment by PavelSindler** [comment]
Fixed in PR https://github.com/prusa3d/Prusa-Firmware/pull/927 and released with [3.3.1](https://github.com/prusa3d/Prusa-Firmware/releases/tag/v3.3.1).
