### ISSUE TITLE
Support of CoreXY printer

### ISSUE THREAD

**Issue by langph** [prusa3d/Prusa-Firmware#939]
I am working on a CoreXY (Hypercube Evolution) printer, based on Prusa parts. I have the Einsy board almost working there is already code in it for CoreXY. I moved define Corexy to Configuration_prusa.h. The only issue I have is that when I move the X stepper in settings it moves the y axis and vice versa. How can this be changed?

**Comment by FischOderAal** [comment]
In case you're still looking: I'd try swapping the X and Y PINs. You can do this in the "pins_Einsy_1_0.h".

**Comment by CuriousTimo** [comment]
Hi Philip,

Is your Hypercube Evolution working at the moment with the MK3 firmware?
I have remixed the MK3 extruder to work on the Hypercube: [https://www.thingiverse.com/thing:3041438](https://www.thingiverse.com/thing:3041438)

Autohome works. And I can calibrate Z. But a full XYZ calibration is not working for me because NEW_XYZCAL is only working for one stepper in sm4.c - simple 4-axis stepper control.
I also had to play around with stallguard sensitivity and running current for Z axis because the bed is heavier than what the steppers need to lift in my MK3.  

Did you get around this or have you disabled NEW_XYZCAL?
